In [1]:
p = 21888242871839275222246405745257275088548364400416034343698204186575808495617

In [2]:
from tensorflow.keras.layers import Input, AveragePooling2D
from tensorflow.keras import Model
import numpy as np

In [3]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 average_pooling2d (AverageP  (None, 2, 2, 3)          0         
 ooling2D)                                                       
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.4697424 , 0.26405168, 0.50556795],
         [0.31879275, 0.10661064, 0.89969558],
         [0.51674454, 0.44716256, 0.84376492],
         [0.70730021, 0.23034467, 0.21298659],
         [0.39270991, 0.26666702, 0.20998017]],

        [[0.06338963, 0.40992356, 0.65531956],
         [0.65641348, 0.61781921, 0.71094249],
         [0.66084759, 0.01212395, 0.96300368],
         [0.05580187, 0.96245161, 0.20798007],
         [0.94943203, 0.05702934, 0.37272236]],

        [[0.35969427, 0.24114588, 0.40254835],
         [0.87560584, 0.29480004, 0.71005672],
         [0.89799237, 0.03862642, 0.41636709],
         [0.60385376, 0.00368971, 0.73375191],
         [0.39912794, 0.02359739, 0.58151196]],

        [[0.75162628, 0.57732706, 0.51714415],
         [0.42886868, 0.4817775 , 0.55461973],
         [0.96844644, 0.72937866, 0.96170145],
         [0.09311228, 0.70769801, 0.37766384],
         [0.22594407, 0.64493633, 0.84161072]],

        [[0.94736999, 0.95913254, 0.66551587],
     

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 28ms/step


2023-10-23 19:58:12.306880: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[0.37708455, 0.34960127, 0.6928814 ],
         [0.48517358, 0.41302067, 0.5569338 ]],

        [[0.6039488 , 0.39876258, 0.5460923 ],
         [0.6408512 , 0.3698482 , 0.6223711 ]]]], dtype=float32)

In [7]:
def AveragePooling2DInt (nRows, nCols, nChannels, poolSize, strides, input):
    Input = [[[str(input[i][j][k] % p) for k in range(nChannels)] for j in range(nCols)] for i in range(nRows)]
    out = [[[0 for _ in range(nChannels)] for _ in range((nCols-poolSize)//strides + 1)] for _ in range((nRows-poolSize)//strides + 1)]
    remainder = [[[None for _ in range(nChannels)] for _ in range((nCols-poolSize)//strides + 1)] for _ in range((nRows-poolSize)//strides + 1)]
    for i in range((nRows-poolSize)//strides + 1):
        for j in range((nCols-poolSize)//strides + 1):
            for k in range(nChannels):
                for x in range(poolSize):
                    for y in range(poolSize):
                        out[i][j][k] += input[i*strides+x][j*strides+y][k]
                remainder[i][j][k] = str(out[i][j][k] % poolSize**2 % p)
                out[i][j][k] = str(out[i][j][k] // poolSize**2 % p)
    return Input, out, remainder

In [8]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(5)] for i in range(5)]

In [9]:
X_in, out, remainder = AveragePooling2DInt(5, 5, 3, 2, 2, X_in)
out, remainder

([[['377084566964233814727207747512696832',
    '349601274166158063422211165597466624',
    '692881395085479491591287820028739584'],
   ['485173550880783982864257598131011584',
    '413020696901266553234304779809718272',
    '556933813298750165384079226175488000']],
  [['603948769893606922513439699094208512',
    '398762621026204510661452706879635456',
    '546092235924829818623026255726903296'],
   ['640851212450790063364758949182046208',
    '369848200094279040953444891822653440',
    '622371069389430669959468896315506688']]],
 [[['0', '0', '0'], ['0', '0', '0']], [['0', '0', '0'], ['0', '0', '0']]])

In [10]:
in_json = {
    "in": X_in,
    "out": out,
    "remainder": remainder 
}

In [11]:
import json

In [12]:
with open("averagePooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [13]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=3, strides=2)(inputs)
model = Model(inputs, x)

In [14]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 average_pooling2d_1 (Averag  (None, 4, 4, 3)          0         
 ePooling2D)                                                     
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [15]:
X = np.random.rand(1,10,10,3)

In [16]:
y = model.predict(X)
y

1/1 [==============================] - 0s 20ms/step


array([[[[0.49083894, 0.6503702 , 0.45121744],
         [0.3731585 , 0.55850077, 0.5209063 ],
         [0.392081  , 0.4962937 , 0.44958603],
         [0.5062166 , 0.5363207 , 0.5836957 ]],

        [[0.4387001 , 0.51550937, 0.4842767 ],
         [0.36599833, 0.6358112 , 0.42103994],
         [0.45892367, 0.48430002, 0.48299968],
         [0.47987926, 0.51054746, 0.48522002]],

        [[0.4337698 , 0.5966541 , 0.34484175],
         [0.50603914, 0.54209197, 0.3464988 ],
         [0.5383602 , 0.40848657, 0.5954534 ],
         [0.39340922, 0.5384207 , 0.6712477 ]],

        [[0.52239245, 0.61681217, 0.5948292 ],
         [0.6456814 , 0.56172687, 0.5704497 ],
         [0.5970895 , 0.65395427, 0.61463684],
         [0.49751964, 0.57090425, 0.50965226]]]], dtype=float32)

In [17]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(10)] for i in range(10)]

In [18]:
X_in, out, remainder = AveragePooling2DInt(10, 10, 3, 3, 2, X_in)
out, remainder

([[['490838913202839647482031788613930552',
    '650370206452327739765809362325238215',
    '451217443243932157150820354890924032'],
   ['373158499178459549901037286246696732',
    '558500757386374812373354359379751367',
    '520906395265463287758066336793158542'],
   ['392081032582640205401569336636735488',
    '496293715863929836162024945736366307',
    '449586010677657401563374125861539384'],
   ['506216538770442893696705511483535815',
    '536320651604328640569669741910920760',
    '583695794530695154314058797408758442']],
  [['438700122269240629018040116487826090',
    '515509373055967873846597732290585486',
    '484276697106518139982691888834194090'],
   ['365998311298275897695359121353838136',
    '635811225512657877386382358476401322',
    '421039958668517212332658528902359722'],
   ['458923652827692860008536397550744007',
    '484300011977437346144682467789664711',
    '482999719051088512471698660426980465'],
   ['479879293099700576539663622281305201',
    '5105474985000666986

In [19]:
in_json = {
    "in": X_in,
    "out": out,
    "remainder": remainder
}

In [20]:
with open("averagePooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)