In [1]:
from tensorflow.keras.layers import Input, AveragePooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
average_pooling2d (AveragePo (None, 2, 2, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.79941942, 0.74789538, 0.59164868],
         [0.25731687, 0.43079569, 0.67277259],
         [0.10620233, 0.85056582, 0.27951353],
         [0.23562352, 0.39038001, 0.79778411],
         [0.8357717 , 0.97955005, 0.7266173 ]],

        [[0.51417529, 0.8118348 , 0.24336546],
         [0.25096464, 0.96328609, 0.61843696],
         [0.119168  , 0.04735649, 0.81364784],
         [0.63780521, 0.54847675, 0.78713755],
         [0.90202837, 0.03890637, 0.91213939]],

        [[0.35266164, 0.08792946, 0.85172066],
         [0.26321742, 0.46759433, 0.68288282],
         [0.40252278, 0.65572821, 0.78984132],
         [0.01883342, 0.72079971, 0.71303053],
         [0.81122497, 0.27290105, 0.04123257]],

        [[0.47782615, 0.03275952, 0.658033  ],
         [0.91941939, 0.36194587, 0.67565511],
         [0.33704936, 0.99096846, 0.47735187],
         [0.72613102, 0.56987187, 0.13081093],
         [0.22415976, 0.24756073, 0.3059867 ]],

        [[0.56391481, 0.4201842 , 0.12265913],
     

In [5]:
y = model.predict(X)
y

array([[[[0.45546904, 0.73845303, 0.5315559 ],
         [0.27469975, 0.45919478, 0.6695208 ]],

        [[0.5032811 , 0.23755729, 0.71707296],
         [0.37113416, 0.7343421 , 0.52775866]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [7]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [8]:
import json

In [9]:
with open("averagePooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [10]:
with open("averagePooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [11]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=3, strides=2)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 10, 3)]       0         
_________________________________________________________________
average_pooling2d_1 (Average (None, 4, 4, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [13]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.22890555, 0.85041378, 0.06779732],
         [0.48589264, 0.02266948, 0.40622616],
         [0.44445561, 0.14270991, 0.52828695],
         [0.97840965, 0.77211542, 0.38526407],
         [0.50635591, 0.8181549 , 0.55638397],
         [0.5286157 , 0.99152978, 0.94160218],
         [0.43308486, 0.61300801, 0.01441346],
         [0.41196092, 0.66083358, 0.50274479],
         [0.43239334, 0.36299657, 0.75523639],
         [0.79494342, 0.54508873, 0.50525316]],

        [[0.9020999 , 0.24772335, 0.47150931],
         [0.89449072, 0.3000441 , 0.08307242],
         [0.01358907, 0.42335199, 0.25529873],
         [0.96579533, 0.61313033, 0.61151241],
         [0.25208166, 0.08639203, 0.21649145],
         [0.92453334, 0.99969662, 0.967767  ],
         [0.5433799 , 0.8949675 , 0.42470272],
         [0.21281325, 0.31257917, 0.76526748],
         [0.27621526, 0.51521548, 0.63729558],
         [0.07299284, 0.48444809, 0.33561529]],

        [[0.70601855, 0.8317636 , 0.72355013],
         

In [14]:
y = model.predict(X)
y

array([[[[0.48165163, 0.40772024, 0.3972965 ],
         [0.55030197, 0.4651319 , 0.40548024],
         [0.5464923 , 0.64114237, 0.5255094 ],
         [0.3323996 , 0.5333504 , 0.4773672 ]],

        [[0.42013475, 0.5276699 , 0.48012605],
         [0.6024354 , 0.4213521 , 0.441346  ],
         [0.44936445, 0.43590552, 0.43433058],
         [0.38311118, 0.46002626, 0.4891111 ]],

        [[0.440164  , 0.5174649 , 0.36716762],
         [0.6406646 , 0.39124662, 0.33782133],
         [0.6299255 , 0.49198008, 0.3468656 ],
         [0.5842741 , 0.3953741 , 0.39856434]],

        [[0.46311432, 0.544752  , 0.30419722],
         [0.53188324, 0.47697794, 0.26368374],
         [0.49155417, 0.54867196, 0.48500708],
         [0.5358231 , 0.40043873, 0.39848566]]]], dtype=float32)

In [15]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [16]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [17]:
with open("averagePooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [18]:
with open("averagePooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)