In [1]:
from tensorflow.keras.layers import Input, AveragePooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 average_pooling2d (AverageP  (None, 2, 2, 3)          0         
 ooling2D)                                                       
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = (np.random.rand(1,5,5,3)*1000).round().astype(int)
X

array([[[[  8, 188, 727],
         [ 25, 496, 796],
         [710, 913, 379],
         [150, 426, 202],
         [401, 251, 386]],

        [[386, 176, 769],
         [797, 221, 590],
         [587, 814, 720],
         [775, 854, 745],
         [682, 167, 211]],

        [[787,  56, 751],
         [518, 593, 852],
         [269,  96, 478],
         [112,  51, 603],
         [954, 399,   6]],

        [[455, 610, 699],
         [ 48, 907, 522],
         [ 67, 684, 839],
         [407, 105, 656],
         [412, 539, 868]],

        [[670,   1, 790],
         [859, 644, 904],
         [676, 691, 369],
         [ 21, 583, 281],
         [811, 785, 392]]]])

In [5]:
y = model.predict(X)
y

1/1 [==============================] - 0s 48ms/step


2023-10-21 22:46:19.213599: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[304.  , 270.25, 720.5 ],
         [555.5 , 751.75, 511.5 ]],

        [[452.  , 541.5 , 706.  ],
         [213.75, 234.  , 644.  ]]]], dtype=float32)

In [6]:
out = np.floor(y).astype(int)
out

array([[[[304, 270, 720],
         [555, 751, 511]],

        [[452, 541, 706],
         [213, 234, 644]]]])

In [7]:
remainder = (y * 4 - out * 4).round().astype(int)
remainder

array([[[[0, 1, 2],
         [2, 3, 2]],

        [[0, 2, 0],
         [3, 0, 0]]]])

In [8]:
in_json = {
    "in": X.flatten().tolist(),
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [9]:
import json

In [10]:
with open("averagePooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=3, strides=2)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 average_pooling2d_1 (Averag  (None, 4, 4, 3)          0         
 ePooling2D)                                                     
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [13]:
X = (np.random.rand(1,10,10,3)*1000).round().astype(int)
X

array([[[[ 418,  534,  957],
         [ 716,  944,  423],
         [ 354,  287,  223],
         [ 272,  420,  117],
         [ 114,  821,  898],
         [ 139,  741,  120],
         [ 599,  319,  700],
         [ 306,  569,  897],
         [ 741,  426,  237],
         [  96,  903,  933]],

        [[ 486,  283,  191],
         [ 991,  849,  969],
         [ 200,  493,  453],
         [ 997,  189,  112],
         [ 325,  738,   57],
         [ 533,  181,   31],
         [ 633,  160,    0],
         [ 536,   54,  691],
         [ 189,  293,  606],
         [ 156,  267,  382]],

        [[ 309,   80,  760],
         [ 628,  865,  904],
         [ 867,  949,  533],
         [ 698,  584,  818],
         [ 715,  905,  185],
         [ 482,   28,  848],
         [ 887,  290,  186],
         [ 543,   76,  685],
         [  86,  445,  781],
         [ 650,  731,  130]],

        [[ 171,  501,  211],
         [ 241,  928,  213],
         [  76,  232,  725],
         [  83,  646,  726],
        

In [14]:
y = model.predict(X)
y

1/1 [==============================] - 0s 30ms/step


array([[[[552.1111 , 587.1111 , 601.44446],
         [504.66666, 598.44446, 377.33334],
         [491.8889 , 464.77777, 336.1111 ],
         [502.22223, 292.44446, 531.44446]],

        [[427.55554, 530.8889 , 499.8889 ],
         [445.     , 575.55554, 583.55554],
         [493.77777, 518.44446, 345.22223],
         [551.55554, 449.55554, 490.33334]],

        [[540.44446, 614.55554, 453.1111 ],
         [535.     , 623.55554, 475.44446],
         [412.33334, 478.66666, 489.1111 ],
         [464.8889 , 467.8889 , 514.3333 ]],

        [[677.6667 , 562.     , 536.     ],
         [532.7778 , 756.8889 , 603.1111 ],
         [425.33334, 406.22223, 702.3333 ],
         [525.6667 , 589.2222 , 586.3333 ]]]], dtype=float32)

In [15]:
out = np.floor(y).astype(int)
out

array([[[[552, 587, 601],
         [504, 598, 377],
         [491, 464, 336],
         [502, 292, 531]],

        [[427, 530, 499],
         [445, 575, 583],
         [493, 518, 345],
         [551, 449, 490]],

        [[540, 614, 453],
         [535, 623, 475],
         [412, 478, 489],
         [464, 467, 514]],

        [[677, 562, 536],
         [532, 756, 603],
         [425, 406, 702],
         [525, 589, 586]]]])

In [16]:
remainder = (y * 9 - out * 9).round().astype(int)
remainder

array([[[[1, 1, 4],
         [6, 4, 3],
         [8, 7, 1],
         [2, 4, 4]],

        [[5, 8, 8],
         [0, 5, 5],
         [7, 4, 2],
         [5, 5, 3]],

        [[4, 5, 1],
         [0, 5, 4],
         [3, 6, 1],
         [8, 8, 3]],

        [[6, 0, 0],
         [7, 8, 1],
         [3, 2, 3],
         [6, 2, 3]]]])

In [17]:
in_json = {
    "in": X.flatten().tolist(),
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [18]:
with open("averagePooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)