In [3]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [7]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [8]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
batch_normalization_2 (Batch (None, 5, 5, 3)           12        
_________________________________________________________________
flatten_1 (Flatten)          (None, 75)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 76        
Total params: 88
Trainable params: 82
Non-trainable params: 6
_________________________________________________________________


In [9]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.19552316, 0.40459235, 0.65069767],
         [0.97024076, 0.81831547, 0.5177182 ],
         [0.05950918, 0.03350272, 0.9602491 ],
         [0.08329085, 0.30977063, 0.72642731],
         [0.54523607, 0.01088976, 0.82204523]],

        [[0.54181334, 0.16416867, 0.26710512],
         [0.97727194, 0.83483966, 0.24119749],
         [0.31456203, 0.78914841, 0.65570909],
         [0.82076783, 0.80354282, 0.08698502],
         [0.15471074, 0.02844633, 0.95682819]],

        [[0.98696698, 0.95562821, 0.93463443],
         [0.82143354, 0.56738999, 0.41847729],
         [0.23732813, 0.73090915, 0.52152988],
         [0.66008344, 0.19977572, 0.46451022],
         [0.65939235, 0.70715058, 0.12179132]],

        [[0.89408023, 0.76606208, 0.89090992],
         [0.07624889, 0.99371095, 0.1459594 ],
         [0.93944538, 0.47966536, 0.06641057],
         [0.48141466, 0.88173281, 0.45451347],
         [0.68325521, 0.81211422, 0.6974409 ]],

        [[0.45623391, 0.24889916, 0.48213288],
     

In [10]:
y_train = np.random.rand(100,1)
y_train

array([[0.41246058],
       [0.20653047],
       [0.89323387],
       [0.77751859],
       [0.71370253],
       [0.95423612],
       [0.73784913],
       [0.26439079],
       [0.98359435],
       [0.31472127],
       [0.93990584],
       [0.13038553],
       [0.66315094],
       [0.99092294],
       [0.00492079],
       [0.33818935],
       [0.81103904],
       [0.70299052],
       [0.98968483],
       [0.30019187],
       [0.07267281],
       [0.07848536],
       [0.09338778],
       [0.12276658],
       [0.55228728],
       [0.64323192],
       [0.56388056],
       [0.16935227],
       [0.59849839],
       [0.0426659 ],
       [0.28957528],
       [0.42632845],
       [0.3771928 ],
       [0.73206006],
       [0.24224496],
       [0.29938391],
       [0.89107997],
       [0.4720799 ],
       [0.29481523],
       [0.81441205],
       [0.1567971 ],
       [0.49008399],
       [0.23646704],
       [0.62417537],
       [0.53533012],
       [0.36987479],
       [0.79447313],
       [0.358

In [11]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 [==============================] - 0s 566us/step - loss: 1.7214
Epoch 2/10
4/4 [==============================] - 0s 660us/step - loss: 1.6521
Epoch 3/10
4/4 [==============================] - 0s 1ms/step - loss: 1.6740
Epoch 4/10
4/4 [==============================] - 0s 729us/step - loss: 1.6128
Epoch 5/10
4/4 [==============================] - 0s 1ms/step - loss: 1.4255
Epoch 6/10
4/4 [==============================] - 0s 585us/step - loss: 1.4899
Epoch 7/10
4/4 [==============================] - 0s 1ms/step - loss: 1.3811
Epoch 8/10
4/4 [==============================] - 0s 673us/step - loss: 1.3549
Epoch 9/10
4/4 [==============================] - 0s 653us/step - loss: 1.3313
Epoch 10/10
4/4 [==============================] - 0s 1ms/step - loss: 1.2854


In [12]:
model.layers[1].weights

[<tf.Variable 'batch_normalization_2/gamma:0' shape=(3,) dtype=float32, numpy=array([0.9656307, 0.9650906, 0.9646477], dtype=float32)>,
 <tf.Variable 'batch_normalization_2/beta:0' shape=(3,) dtype=float32, numpy=array([0.03126225, 0.03251555, 0.0313088 ], dtype=float32)>,
 <tf.Variable 'batch_normalization_2/moving_mean:0' shape=(3,) dtype=float32, numpy=array([0.16415757, 0.16638677, 0.16154662], dtype=float32)>,
 <tf.Variable 'batch_normalization_2/moving_variance:0' shape=(3,) dtype=float32, numpy=array([0.6964935 , 0.69624424, 0.6967338 ], dtype=float32)>]

In [17]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.53603175, 0.16288177, 0.54647377],
         [0.58968269, 0.51633636, 0.09084824],
         [0.58954409, 0.60274177, 0.16628126],
         [0.03036366, 0.25776433, 0.97264483],
         [0.06753911, 0.4969747 , 0.02626603]],

        [[0.92805506, 0.92962356, 0.94991846],
         [0.40984699, 0.57242913, 0.73624703],
         [0.27120968, 0.30428539, 0.6547197 ],
         [0.6895789 , 0.12203021, 0.56160566],
         [0.35853814, 0.61396961, 0.30326431]],

        [[0.49895694, 0.26192641, 0.41918769],
         [0.56496371, 0.13934069, 0.77930897],
         [0.9652276 , 0.68000352, 0.59384582],
         [0.18267196, 0.26760574, 0.93864666],
         [0.49916607, 0.63215712, 0.38614211]],

        [[0.46365438, 0.3845917 , 0.6604073 ],
         [0.59669509, 0.22802217, 0.62536791],
         [0.37852067, 0.51773501, 0.96948045],
         [0.46492378, 0.09701206, 0.90831063],
         [0.31265477, 0.43007139, 0.82608669]],

        [[0.32252988, 0.28388506, 0.15159293],
     

In [33]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

array([[[[ 0.4612311 ,  0.02846454,  0.47584018],
         [ 0.5232636 ,  0.4369807 , -0.05033689],
         [ 0.5231033 ,  0.5368464 ,  0.03677658],
         [-0.12343314,  0.13812803,  0.9680018 ],
         [-0.08045009,  0.41460282, -0.12491935]],

        [[ 0.9144969 ,  0.9146502 ,  0.94175637],
         [ 0.31533363,  0.50181156,  0.69499886],
         [ 0.1550382 ,  0.19189616,  0.6008475 ],
         [ 0.63876563, -0.01875092,  0.4933151 ],
         [ 0.25600925,  0.54982334,  0.19497083]],

        [[ 0.41836447,  0.14293846,  0.3288444 ],
         [ 0.49468288,  0.00125621,  0.7447288 ],
         [ 0.9574766 ,  0.62614405,  0.53054756],
         [ 0.05266898,  0.14950253,  0.92873925],
         [ 0.41860625,  0.57084405,  0.29068184]],

        [[ 0.37754688,  0.28471267,  0.6074158 ],
         [ 0.53137136,  0.10375258,  0.5669507 ],
         [ 0.27911344,  0.43859717,  0.96434736],
         [ 0.37901458, -0.04766643,  0.8937058 ],
         [ 0.20295788,  0.33727726,  0.79874

In [34]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [41]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [43]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[-2.03794953e-08,  5.91488761e-09,  1.45154126e-08],
         [ 7.98100520e-08,  1.98810133e-08,  7.91968675e-09],
         [ 4.81973802e-08, -2.20449419e-08, -1.88879183e-09],
         [ 2.64212180e-10,  1.55602272e-08, -7.21641903e-08],
         [-8.82741547e-10, -2.68981404e-08,  1.23617632e-08]],

        [[ 2.51851505e-08, -1.65522146e-08, -4.00145346e-08],
         [ 2.10715177e-08, -7.90676278e-08, -8.24527382e-08],
         [ 5.33205935e-09, -1.58572262e-08,  1.61795255e-09],
         [ 4.38547865e-10,  3.73349793e-09, -5.56143572e-08],
         [ 3.41888787e-08,  3.81396181e-09,  5.69365846e-09]],

        [[ 2.33330081e-08,  6.56881610e-09, -1.21710513e-08],
         [-2.89912733e-09,  4.82403046e-09, -1.72175791e-08],
         [ 6.43033263e-08, -4.13130072e-08, -1.50603818e-09],
         [ 7.43607972e-09,  4.41849135e-09,  2.61667081e-08],
         [ 1.46215137e-08, -6.68016564e-08, -4.45506274e-08]],

        [[ 1.13439502e-08, -1.31488602e-08,  1.62490282e-08],
  

In [44]:
y-(a*X+b)

array([[[[-1.61475423e-08,  5.64923888e-09, -2.40047562e-08],
         [ 8.45288702e-08,  8.12395617e-09, -3.95743559e-09],
         [ 5.29149408e-08, -3.66111857e-08, -1.81769167e-08],
         [-9.26127786e-11,  1.22097854e-08, -1.35605033e-07],
         [-9.02211070e-10, -3.80257174e-08,  4.26113381e-09]],

        [[ 3.29745908e-08, -4.17459400e-08, -1.02126435e-07],
         [ 2.41583839e-08, -9.26483562e-08, -1.32070041e-07],
         [ 7.16083581e-09, -2.07201465e-08, -4.32319784e-08],
         [ 6.06389250e-09,  4.79600271e-09, -9.50193745e-08],
         [ 3.68101333e-08, -1.11173180e-08, -1.86046535e-08]],

        [[ 2.72285189e-08,  3.08305820e-09, -4.32480702e-08],
         [ 1.59537394e-09,  5.32374209e-09, -6.93529612e-08],
         [ 7.24300957e-08, -5.83911616e-08, -4.27963234e-08],
         [ 8.46140438e-09,  7.48088591e-10, -3.52860654e-08],
         [ 1.85189223e-08, -8.23242431e-08, -7.36952816e-08]],

        [[ 1.49191015e-08, -2.06226749e-08, -2.89334895e-08],
  

In [45]:
a

array([1.1562214, 1.1557811, 1.1548455], dtype=float32)

In [46]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "a": (a*1000).round().astype(int).flatten().tolist(),
    "b": (b*1000*1000).round().astype(int).flatten().tolist()
}

In [47]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [48]:
import json

In [49]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)

In [50]:
with open("batchNormalization_output.json", "w") as f:
    json.dump(out_json, f)

In [51]:
X.shape

(1, 5, 5, 3)

In [52]:
a.shape

(3,)

In [53]:
b.shape

(3,)