In [1]:
p = 21888242871839275222246405745257275088548364400416034343698204186575808495617

In [2]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [3]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 batch_normalization (BatchN  (None, 5, 5, 3)          12        
 ormalization)                                                   
                                                                 
 flatten (Flatten)           (None, 75)                0         
                                                                 
 dense (Dense)               (None, 1)                 76        
                                                                 
Total params: 88
Trainable params: 82
Non-trainable params: 6
_________________________________________________________________


In [5]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.51546565, 0.46651282, 0.78133227],
         [0.29092001, 0.15424294, 0.31568105],
         [0.42554169, 0.17798232, 0.88401623],
         [0.89061342, 0.56954272, 0.0481971 ],
         [0.91385411, 0.87839928, 0.54333657]],

        [[0.06954288, 0.9189417 , 0.16824991],
         [0.61834797, 0.48611683, 0.05698664],
         [0.54958275, 0.40614748, 0.93471022],
         [0.96738304, 0.9310907 , 0.05346684],
         [0.01504873, 0.45594357, 0.92055095]],

        [[0.11021081, 0.40673465, 0.56412873],
         [0.5385549 , 0.06119234, 0.5499304 ],
         [0.409637  , 0.72651771, 0.71666944],
         [0.99635655, 0.13653654, 0.10949123],
         [0.2601131 , 0.70956364, 0.51173637]],

        [[0.29500952, 0.50029805, 0.48711255],
         [0.58302715, 0.07682466, 0.06070311],
         [0.63143749, 0.55553472, 0.62363371],
         [0.34286961, 0.28562232, 0.10381272],
         [0.5267341 , 0.44532117, 0.74259914]],

        [[0.89833895, 0.70393118, 0.3390096 ],
     

In [6]:
y_train = np.random.rand(100,1)
y_train

array([[0.21946477],
       [0.3711923 ],
       [0.24737705],
       [0.16344551],
       [0.57433513],
       [0.76673914],
       [0.7049643 ],
       [0.67571894],
       [0.15141958],
       [0.84983105],
       [0.05552415],
       [0.95604334],
       [0.70679183],
       [0.86247509],
       [0.01407803],
       [0.55736261],
       [0.19422897],
       [0.86008897],
       [0.2779906 ],
       [0.55527211],
       [0.16247257],
       [0.13970005],
       [0.92248072],
       [0.93564244],
       [0.28634139],
       [0.23594509],
       [0.44848018],
       [0.35401733],
       [0.99775489],
       [0.1732102 ],
       [0.81910272],
       [0.46522896],
       [0.99489404],
       [0.55781089],
       [0.13592596],
       [0.43879534],
       [0.81024602],
       [0.94877655],
       [0.75248092],
       [0.30265859],
       [0.42836091],
       [0.59454105],
       [0.43154069],
       [0.67468033],
       [0.58606549],
       [0.1744458 ],
       [0.49333982],
       [0.067

In [7]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
4/4 [==============================] - 0s 2ms/step - loss: 2.7752
Epoch 2/10
4/4 [==============================] - 0s 979us/step - loss: 2.6586
Epoch 3/10
4/4 [==============================] - 0s 649us/step - loss: 2.5723
Epoch 4/10
4/4 [==============================] - 0s 2ms/step - loss: 2.4804
Epoch 5/10
4/4 [==============================] - 0s 1ms/step - loss: 2.3874
Epoch 6/10
4/4 [==============================] - 0s 762us/step - loss: 2.2941
Epoch 7/10
4/4 [==============================] - 0s 889us/step - loss: 2.2374
Epoch 8/10


2023-10-23 20:00:14.999431: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


4/4 [==============================] - 0s 15ms/step - loss: 2.1879
Epoch 9/10
4/4 [==============================] - 0s 987us/step - loss: 2.1199
Epoch 10/10
4/4 [==============================] - 0s 1ms/step - loss: 2.0514


In [8]:
model.layers[1].weights

[<tf.Variable 'batch_normalization/gamma:0' shape=(3,) dtype=float32, numpy=array([0.9704942, 0.9639488, 0.9704298], dtype=float32)>,
 <tf.Variable 'batch_normalization/beta:0' shape=(3,) dtype=float32, numpy=array([ 0.02682306, -0.02748435,  0.02756111], dtype=float32)>,
 <tf.Variable 'batch_normalization/moving_mean:0' shape=(3,) dtype=float32, numpy=array([0.16209687, 0.1706537 , 0.16507432], dtype=float32)>,
 <tf.Variable 'batch_normalization/moving_variance:0' shape=(3,) dtype=float32, numpy=array([0.6963565, 0.6966989, 0.6962899], dtype=float32)>]

In [9]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.27455621, 0.27884516, 0.7259278 ],
         [0.53377714, 0.6519488 , 0.86514377],
         [0.49080768, 0.65021787, 0.68419028],
         [0.0618392 , 0.02673969, 0.57868236],
         [0.85494917, 0.71864642, 0.38163087]],

        [[0.22703165, 0.33350008, 0.85208601],
         [0.86850824, 0.43578265, 0.70671478],
         [0.75415054, 0.97444638, 0.48606382],
         [0.14784358, 0.45406111, 0.08556609],
         [0.20530247, 0.25450988, 0.51542351]],

        [[0.13544047, 0.01932561, 0.22823691],
         [0.64891188, 0.18616972, 0.46087849],
         [0.81283055, 0.5325164 , 0.32305024],
         [0.75351508, 0.14501534, 0.44999686],
         [0.42234362, 0.06347228, 0.63881747]],

        [[0.85467296, 0.80260163, 0.14398915],
         [0.57931829, 0.53329564, 0.7187654 ],
         [0.80024988, 0.96224997, 0.8937722 ],
         [0.33025203, 0.91751174, 0.62203916],
         [0.93176317, 0.72790829, 0.14862771]],

        [[0.60466651, 0.567648  , 0.37182924],
     

In [10]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

1/1 [==============================] - 0s 32ms/step


array([[[[ 0.1575187 ,  0.09737267,  0.67934984],
         [ 0.45877463,  0.5279483 ,  0.8411379 ],
         [ 0.40883726,  0.52595073,  0.63084507],
         [-0.0896923 , -0.19356653,  0.50823045],
         [ 0.83202755,  0.60491985,  0.27922952]],

        [[ 0.10228759,  0.16044651,  0.8259631 ],
         [ 0.84778535,  0.2784844 ,  0.65702164],
         [ 0.7148835 ,  0.9001226 ,  0.40059495],
         [ 0.01025847,  0.29957846, -0.06483836],
         [ 0.07703484,  0.06928882,  0.43471497]],

        [[-0.00415592, -0.20212264,  0.10096472],
         [ 0.5925795 , -0.00957828,  0.37132615],
         [ 0.7830791 ,  0.39011884,  0.21115081],
         [ 0.714145  , -0.05707199,  0.3586802 ],
         [ 0.32927114, -0.15117574,  0.5781157 ]],

        [[ 0.8317066 ,  0.7018073 ,  0.00305727],
         [ 0.5117007 ,  0.39101806,  0.6710261 ],
         [ 0.7684583 ,  0.88604754,  0.8744081 ],
         [ 0.22224607,  0.83441794,  0.558617  ],
         [ 0.92129767,  0.6156084 ,  0.00844

In [11]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [12]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [13]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[ 1.38897775e-08, -4.41621682e-09, -1.46314817e-08],
         [ 1.22362858e-08,  2.73325588e-08, -4.77779197e-08],
         [-1.14818392e-08, -8.60447691e-09, -5.83081214e-08],
         [-5.10371694e-09, -8.67723293e-09,  2.98262304e-10],
         [-7.37144357e-09, -6.87929902e-09, -3.09108445e-08]],

        [[-3.70238870e-09,  9.08749898e-09,  6.04406457e-08],
         [-8.04363320e-09, -2.61427017e-08, -4.75678711e-08],
         [-2.29807172e-08, -3.35601555e-08, -3.61847423e-08],
         [ 1.76612667e-09, -8.73801476e-10,  2.36584587e-09],
         [ 5.96964625e-09, -1.35698691e-08, -2.09152273e-09]],

        [[-2.18008088e-09,  3.40718009e-09,  1.14725877e-09],
         [ 7.83470533e-09, -4.13062541e-09, -2.05064118e-08],
         [ 5.68865103e-08,  3.01907888e-08, -1.38190100e-08],
         [-2.30006845e-08, -8.84019241e-09, -3.75235497e-08],
         [-1.33667987e-08,  2.45791437e-09,  1.05576055e-08]],

        [[ 1.63983768e-08,  4.34060976e-09,  7.69416812e-09],
  

In [14]:
y-(a*X+b)

array([[[[ 6.29271463e-09, -1.51612348e-08,  4.78305939e-09],
         [ 2.53706245e-09,  1.56956936e-08, -2.51350980e-08],
         [-2.08326003e-08, -2.02372046e-08, -3.98614322e-08],
         [-1.09757444e-08, -1.88196314e-08,  1.62983274e-08],
         [-1.96752217e-08, -1.86755947e-08, -1.94802087e-08]],

        [[-1.09140497e-08, -1.78816328e-09,  8.27806710e-08],
         [-2.04573691e-08, -3.72628548e-08, -2.85988609e-08],
         [-3.44670656e-08, -4.59679019e-08, -2.23324095e-08],
         [-4.80335610e-09, -1.20376463e-08,  6.93103225e-09],
         [-1.06580120e-09, -2.42567173e-08,  1.24416322e-08]],

        [[-8.64898020e-09, -6.71749611e-09,  9.02084041e-09],
         [-2.79820678e-09, -1.46541169e-08, -7.23810212e-09],
         [ 4.49242945e-08,  1.88394085e-08, -3.74680098e-09],
         [-3.44818796e-08, -1.92653107e-08, -2.45075741e-08],
         [-2.21623482e-08, -7.77228767e-09,  2.79521442e-08]],

        [[ 4.09683865e-09, -7.65636798e-09,  1.36141277e-08],
  

In [15]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(5)] for i in range(5)]
a_in = [int(a[i]*1e36) for i in range(3)]
b_in = [int(b[i]*1e72) for i in range(3)]

In [16]:
def BatchNormalizationInt(nRows, nCols, nChannels, n, X_in, a_in, b_in):
    X = [[[str(X_in[i][j][k] % p) for k in range(nChannels)] for j in range(nCols)] for i in range(nRows)]
    A = [str(a_in[k] % p) for k in range(nChannels)]
    B = [str(b_in[k] % p) for k in range(nChannels)]
    out = [[[None for _ in range(nChannels)] for _ in range(nCols)] for _ in range(nRows)]
    remainder = [[[None for _ in range(nChannels)] for _ in range(nCols)] for _ in range(nRows)]
    for i in range(nRows):
        for j in range(nCols):
            for k in range(nChannels):
                out[i][j][k] = (X_in[i][j][k]*a_in[k] + b_in[k])
                remainder[i][j][k] = str(out[i][j][k] % n)
                out[i][j][k] = str(out[i][j][k] // n % p)
    return X, A, B, out, remainder

In [17]:
X_in, a_in, b_in, out, remainder = BatchNormalizationInt(5, 5, 3, 10**36, X_in, a_in, b_in)
out, remainder

([[['157518693472490790243750538747957882',
    '97372681162554733176887955075564208',
    '679349834904288174010983420548472594'],
   ['458774623717973004897590573896222594',
    '527948304216263291457870336316333444',
    '841137911182461164557826291121517336'],
   ['408837279648365652067755038590177210',
    '525950750084159001810559673300027574',
    '630845109746686169695072155498068928'],
   ['21888242871839275222246405745257275088548274708124961881757683904418357553907',
    '21888242871839275222246405745257275088548170833903911058199291157862382757945',
    '508230431470837755985412821877993851'],
   ['832027574187245701393604967574752718',
    '604919869501858267645833548353564313',
    '279229541231612628393358090302516442']],
  [['102287601417742280387289538163651204',
    '160446511507058261099060517183710523',
    '825962997148680811368987640325934077'],
   ['847785374117952740336862359672140583',
    '278484441349921535654657902103684959',
    '657021670330123182657390893

In [18]:
in_json = {
    "in": X_in,
    "a": a_in,
    "b": b_in,
    "out": out,
    "remainder": remainder
}

In [19]:
import json

In [20]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)