In [1]:
from tensorflow.keras.layers import Input, BatchNormalization, Dense, Flatten
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
out = BatchNormalization()(inputs)
out = Flatten()(out)
out = Dense(1)(out)
model = Model(inputs, out)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 batch_normalization (BatchN  (None, 5, 5, 3)          12        
 ormalization)                                                   
                                                                 
 flatten (Flatten)           (None, 75)                0         
                                                                 
 dense (Dense)               (None, 1)                 76        
                                                                 
Total params: 88
Trainable params: 82
Non-trainable params: 6
_________________________________________________________________


In [4]:
X_train = np.random.rand(100,5,5,3)
X_train

array([[[[0.82274912, 0.40736054, 0.68498523],
         [0.8230278 , 0.36372594, 0.92358726],
         [0.11222973, 0.87605683, 0.85578498],
         [0.95510738, 0.13207973, 0.02499794],
         [0.66215396, 0.88280016, 0.71070054]],

        [[0.62101552, 0.07847336, 0.47203901],
         [0.13353163, 0.62962784, 0.10446926],
         [0.55009024, 0.40978536, 0.10114294],
         [0.26501705, 0.6726599 , 0.1475553 ],
         [0.5379881 , 0.77612225, 0.3094666 ]],

        [[0.78081637, 0.21153126, 0.79208361],
         [0.01910496, 0.38741944, 0.58785852],
         [0.76366579, 0.29651435, 0.54523693],
         [0.96832777, 0.46266453, 0.51650257],
         [0.160083  , 0.37733858, 0.31676244]],

        [[0.24474146, 0.32624459, 0.48975664],
         [0.97247519, 0.08279444, 0.38365329],
         [0.08668803, 0.46132004, 0.25872813],
         [0.70464739, 0.68290626, 0.24096506],
         [0.0916093 , 0.62299643, 0.98366868]],

        [[0.43398222, 0.75998303, 0.72970675],
     

In [5]:
y_train = np.random.rand(100,1)
y_train

array([[0.58154689],
       [0.97276568],
       [0.03616919],
       [0.92173643],
       [0.99861224],
       [0.81982253],
       [0.74981428],
       [0.16758767],
       [0.95489728],
       [0.39514955],
       [0.36229221],
       [0.54150234],
       [0.80688185],
       [0.70711354],
       [0.59369478],
       [0.34841074],
       [0.47580795],
       [0.40434911],
       [0.75228053],
       [0.65517228],
       [0.59748909],
       [0.05689205],
       [0.04695113],
       [0.41211611],
       [0.99520896],
       [0.40803152],
       [0.16918648],
       [0.65492626],
       [0.57095797],
       [0.39814805],
       [0.52472788],
       [0.66899727],
       [0.85448599],
       [0.87601359],
       [0.82514053],
       [0.97999659],
       [0.0619433 ],
       [0.97739788],
       [0.35767672],
       [0.15242683],
       [0.04035593],
       [0.66309975],
       [0.31479638],
       [0.80329615],
       [0.06293182],
       [0.63431576],
       [0.03571975],
       [0.471

In [6]:
model.compile("adam", "mse")
model.fit(X_train, y_train, epochs=10)

Epoch 1/10


2023-10-21 23:09:25.734382: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


4/4 [==============================] - 0s 2ms/step - loss: 2.3616
Epoch 2/10
4/4 [==============================] - 0s 891us/step - loss: 2.2817
Epoch 3/10
4/4 [==============================] - 0s 1ms/step - loss: 2.2055
Epoch 4/10
4/4 [==============================] - 0s 911us/step - loss: 2.1407
Epoch 5/10
4/4 [==============================] - 0s 944us/step - loss: 2.0523
Epoch 6/10
4/4 [==============================] - 0s 898us/step - loss: 1.9939
Epoch 7/10
4/4 [==============================] - 0s 985us/step - loss: 1.9136
Epoch 8/10
4/4 [==============================] - 0s 876us/step - loss: 1.8566
Epoch 9/10
4/4 [==============================] - 0s 847us/step - loss: 1.8013
Epoch 10/10
4/4 [==============================] - 0s 860us/step - loss: 1.7463


In [7]:
model.layers[1].weights

[<tf.Variable 'batch_normalization/gamma:0' shape=(3,) dtype=float32, numpy=array([0.96631116, 0.96508086, 0.9711695 ], dtype=float32)>,
 <tf.Variable 'batch_normalization/beta:0' shape=(3,) dtype=float32, numpy=array([ 0.03545798, -0.03666276, -0.03517246], dtype=float32)>,
 <tf.Variable 'batch_normalization/moving_mean:0' shape=(3,) dtype=float32, numpy=array([0.16947976, 0.1678878 , 0.16330102], dtype=float32)>,
 <tf.Variable 'batch_normalization/moving_variance:0' shape=(3,) dtype=float32, numpy=array([0.69752216, 0.69642395, 0.6965147 ], dtype=float32)>]

In [8]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.18058081, 0.76239732, 0.32088712],
         [0.71733176, 0.09572909, 0.75323131],
         [0.7460153 , 0.75885184, 0.03398817],
         [0.25220535, 0.18497709, 0.36407245],
         [0.26747193, 0.2427972 , 0.36830688]],

        [[0.65613832, 0.38682815, 0.25828609],
         [0.52606132, 0.19540937, 0.51989304],
         [0.02139047, 0.90430195, 0.19640344],
         [0.28528828, 0.52514387, 0.01089654],
         [0.8956268 , 0.87346085, 0.10971723]],

        [[0.42439006, 0.05803118, 0.79078099],
         [0.62080625, 0.57190244, 0.35542104],
         [0.16965143, 0.5709051 , 0.53500808],
         [0.88723258, 0.87530955, 0.00890318],
         [0.00526431, 0.2144928 , 0.26502846]],

        [[0.52638211, 0.13999985, 0.91684388],
         [0.42050272, 0.38722008, 0.5520409 ],
         [0.6271974 , 0.27592556, 0.58837879],
         [0.41508305, 0.32870619, 0.33543989],
         [0.01288278, 0.40794355, 0.6946529 ]],

        [[0.09057427, 0.48131355, 0.41053933],
     

In [9]:
new_model = Model(inputs, model.layers[1].output)
y = new_model.predict(X)
y

1/1 [==============================] - 0s 48ms/step


array([[[[ 0.04829284,  0.65036464,  0.14807427],
         [ 0.66887563, -0.12005086,  0.6508195 ],
         [ 0.70203906,  0.6462674 , -0.18554205],
         [ 0.13110396, -0.01691404,  0.19829169],
         [ 0.14875495,  0.04990407,  0.20321566]],

        [[ 0.5981247 ,  0.21634921,  0.07527956],
         [ 0.4477318 , -0.00485827,  0.37948543],
         [-0.13576046,  0.8143526 ,  0.0033202 ],
         [ 0.16935392,  0.37618968, -0.21239382],
         [ 0.87501746,  0.7787119 , -0.09748159]],

        [[ 0.33018112, -0.16361533,  0.6944835 ],
         [ 0.5572744 ,  0.4302249 ,  0.18823153],
         [ 0.03565646,  0.42907232,  0.39706174],
         [ 0.86531216,  0.7808483 , -0.21471176],
         [-0.15440527,  0.01719493,  0.08311982]],

        [[ 0.4481027 , -0.06889066,  0.84107405],
         [ 0.3256867 ,  0.21680215,  0.4168681 ],
         [ 0.5646637 ,  0.08818787,  0.4591231 ],
         [ 0.31942052,  0.14918229,  0.16499674],
         [-0.1455969 ,  0.24075058,  0.58270

In [10]:
gamma = model.layers[1].weights[0].numpy()
beta = model.layers[1].weights[1].numpy()
moving_mean = model.layers[1].weights[2].numpy()
moving_var = model.layers[1].weights[3].numpy()
epsilon = model.layers[1].epsilon

In [11]:
a = gamma/(moving_var+epsilon)**.5
b = beta-gamma*moving_mean/(moving_var+epsilon)**.5

In [12]:
y-(gamma*(X-moving_mean)/((moving_var+epsilon)**.5)+beta)

array([[[[-5.02962781e-09, -3.04437784e-08,  1.98399722e-09],
         [ 1.56565487e-08, -5.25468524e-09, -1.25659017e-08],
         [-3.31383587e-09, -2.23583381e-08, -4.48079177e-09],
         [-1.69087503e-08, -1.35142361e-09, -2.20821304e-08],
         [ 3.18478122e-09, -3.32112422e-09, -2.07347645e-09]],

        [[-6.72399212e-08,  2.49927684e-09, -4.43807245e-09],
         [-3.65339411e-08,  7.72281061e-09, -1.65375608e-08],
         [ 7.17684040e-09, -1.02606090e-08, -9.85223760e-09],
         [-6.83271612e-09, -2.63753415e-08, -7.23521013e-09],
         [ 2.87978974e-10, -6.09301626e-08, -2.10904294e-09]],

        [[-3.03727695e-08,  4.34326217e-09, -7.45857290e-08],
         [ 1.57253808e-08,  2.79570688e-08, -1.14511932e-08],
         [-7.45511403e-09,  9.02534769e-10, -1.36213130e-08],
         [-3.66560283e-08, -4.37172304e-08,  4.59036856e-09],
         [-5.54593435e-09, -1.35482395e-09, -1.42212658e-08]],

        [[-1.04455833e-10, -6.22553673e-09,  3.05781704e-08],
  

In [13]:
y-(a*X+b)

array([[[[ 1.38643053e-09, -3.69041404e-08,  3.45406015e-09],
         [ 2.41986872e-08, -1.98274730e-08, -6.02951278e-09],
         [ 5.34191857e-09, -2.88618437e-08, -6.37268810e-09],
         [-1.02089859e-08, -1.48381873e-08, -2.01060101e-08],
         [ 9.94501681e-09, -1.61042976e-08, -4.77358708e-11]],

        [[-5.89401711e-08, -8.53123988e-09, -3.70158521e-09],
         [-2.87494283e-08, -5.63700675e-09, -1.27354928e-08],
         [ 1.29623429e-08, -1.49941890e-08, -9.84090801e-09],
         [-1.90963911e-12, -3.57227482e-08, -9.39770040e-09],
         [ 9.53634727e-09, -6.60390358e-08, -3.11352566e-09]],

        [[-2.29909784e-08, -1.06882567e-08, -6.76093229e-08],
         [ 2.38851799e-08,  1.91786489e-08, -9.57645246e-09],
         [-1.08234718e-09, -7.88802146e-09, -9.64212277e-09],
         [-2.74409098e-08, -4.88036076e-08,  2.40451961e-09],
         [ 1.75692211e-10, -1.44824224e-08, -1.34057697e-08]],

        [[ 7.68132757e-09, -2.02596108e-08,  3.90318156e-08],
  

In [14]:
a

array([1.1561838, 1.1556206, 1.1628356], dtype=float32)

In [15]:
X_in = (X*1000).round().astype(int)
a_in = (a*1000).round().astype(int)
b_in = (b*1000*1000).round().astype(int)

In [16]:
res = a_in * X_in + b_in
res

array([[[[  48744,  650195,  148258],
         [ 668360, -119701,  650674],
         [ 701884,  646727, -185523],
         [ 130820,  -16817,  198267],
         [ 148160,   50231,  202919]],

        [[ 597844,  216695,   74989],
         [ 447564,   -5257,  379695],
         [-136216,  814347,    2883],
         [ 168968,  376223, -212272],
         [ 875284,  778511,  -97135]],

        [[ 329652, -163629,  694868],
         [ 557384,  430555,  187800],
         [  36028,  429399,  397140],
         [ 864880,  780823, -214598],
         [-154712,   16707,   83130]],

        [[ 447564,  -68837,  841406],
         [ 326184,  216695,  416911],
         [ 564320,   88379,  458779],
         [ 319248,  149647,  164540],
         [-145464,  240971,  583220]],

        [[ -55296,  325359,  252928],
         [ -36800, -106985,  820472],
         [ 506520, -128949, -145981],
         [ 305376, -204089,  223853],
         [ 210584,  317267, -220413]]]])

In [17]:
out = res // 1000
remainder = res % 1000
out, remainder

(array([[[[  48,  650,  148],
          [ 668, -120,  650],
          [ 701,  646, -186],
          [ 130,  -17,  198],
          [ 148,   50,  202]],
 
         [[ 597,  216,   74],
          [ 447,   -6,  379],
          [-137,  814,    2],
          [ 168,  376, -213],
          [ 875,  778,  -98]],
 
         [[ 329, -164,  694],
          [ 557,  430,  187],
          [  36,  429,  397],
          [ 864,  780, -215],
          [-155,   16,   83]],
 
         [[ 447,  -69,  841],
          [ 326,  216,  416],
          [ 564,   88,  458],
          [ 319,  149,  164],
          [-146,  240,  583]],
 
         [[ -56,  325,  252],
          [ -37, -107,  820],
          [ 506, -129, -146],
          [ 305, -205,  223],
          [ 210,  317, -221]]]]),
 array([[[[744, 195, 258],
          [360, 299, 674],
          [884, 727, 477],
          [820, 183, 267],
          [160, 231, 919]],
 
         [[844, 695, 989],
          [564, 743, 695],
          [784, 347, 883],
          [968,

In [18]:
in_json = {
    "in": X_in.flatten().tolist(),
    "a": a_in.flatten().tolist(),
    "b": b_in.flatten().tolist(),
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist(),
}

In [19]:
import json

In [20]:
with open("batchNormalization_input.json", "w") as f:
    json.dump(in_json, f)