In [1]:
from tensorflow.keras.layers import Input, Conv1D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(20,3))
x = Conv1D(2,4,3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 20, 3)]           0         
_________________________________________________________________
conv1d (Conv1D)              (None, 6, 2)              26        
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv1d/kernel:0' shape=(4, 3, 2) dtype=float32, numpy=
 array([[[ 0.13351655,  0.15176392],
         [ 0.02279764, -0.05288953],
         [ 0.31283128, -0.2973013 ]],
 
        [[ 0.27222842, -0.14998454],
         [ 0.10822219, -0.36693448],
         [ 0.14209783, -0.29082325]],
 
        [[-0.48623034, -0.4235212 ],
         [ 0.07678127,  0.32315302],
         [-0.11050957, -0.03980196]],
 
        [[ 0.26589322,  0.00770217],
         [ 0.11929381,  0.29532135],
         [-0.42807332,  0.03231919]]], dtype=float32)>,
 <tf.Variable 'conv1d/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [5]:
X = np.random.rand(1,20,3)
X

array([[[0.84452152, 0.40819381, 0.90425158],
        [0.65092274, 0.59893334, 0.60028247],
        [0.44949689, 0.254961  , 0.40024966],
        [0.57719296, 0.96000249, 0.08217882],
        [0.66562102, 0.00446413, 0.6464117 ],
        [0.85546508, 0.38582714, 0.8505983 ],
        [0.27450673, 0.201367  , 0.18818527],
        [0.90095107, 0.33781381, 0.84773899],
        [0.36179829, 0.39354172, 0.64100907],
        [0.35045615, 0.37234526, 0.48415795],
        [0.11139122, 0.60499841, 0.58387442],
        [0.87088195, 0.64640523, 0.48402816],
        [0.9638806 , 0.29440207, 0.22027009],
        [0.3764113 , 0.13575624, 0.7720717 ],
        [0.42784105, 0.41073501, 0.28311926],
        [0.66622245, 0.95378854, 0.66375939],
        [0.41543282, 0.37529526, 0.23072244],
        [0.54334445, 0.1388458 , 0.85307472],
        [0.25258015, 0.37725648, 0.75018739],
        [0.75532678, 0.52800654, 0.46152891]]])

In [6]:
y = model.predict(X)
y

array([[[ 0.7218593 , -0.4875301 ],
        [-0.06567734, -0.48088893],
        [ 0.21620643, -0.45382428],
        [ 0.1553162 , -0.5966817 ],
        [ 0.23019192, -0.01706157],
        [-0.05194061, -0.49539083]]], dtype=float32)

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": np.zeros(model.weights[1].numpy().shape).tolist()
}

In [8]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("conv1D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv1D_output.json", "w") as f:
    json.dump(out_json, f)