In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 conv2d (Conv2D)             (None, 3, 3, 2)           56        
                                                                 
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[ 0.32827663, -0.23370622],
          [ 0.29613692,  0.05821159],
          [-0.09726971, -0.36233342]],
 
         [[ 0.36133403, -0.14441502],
          [-0.11433956, -0.3514233 ],
          [ 0.25354022,  0.04712868]],
 
         [[-0.27303195,  0.33820194],
          [-0.19949542,  0.32562608],
          [ 0.35184115,  0.23711419]]],
 
 
        [[[-0.2814421 , -0.2952196 ],
          [-0.22013177, -0.26734367],
          [-0.11688176, -0.16133504]],
 
         [[-0.32483077, -0.15190856],
          [-0.3015778 ,  0.24779564],
          [ 0.09180614, -0.18784633]],
 
         [[ 0.31440783,  0.14258236],
          [ 0.18451071,  0.1874556 ],
          [ 0.2431305 ,  0.19409692]]],
 
 
        [[[ 0.29385436,  0.10874939],
          [-0.18717685,  0.25750494],
          [ 0.14058053,  0.06740373]],
 
         [[ 0.24045742,  0.22728252],
          [-0.21586226, -0.16902515],
          [-0.29192993, -0

In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[5.67577712e-01, 1.05832520e-01, 5.42462969e-01],
         [4.51019110e-01, 4.12912238e-01, 4.66133850e-01],
         [7.23807430e-01, 2.11884048e-01, 1.46164655e-01],
         [9.43981999e-01, 5.06937533e-01, 5.01706263e-01],
         [4.12106730e-01, 1.00034268e-01, 4.03585475e-01]],

        [[1.48928320e-01, 9.02537502e-01, 7.30787954e-01],
         [3.59655304e-02, 3.03798072e-01, 7.16231094e-01],
         [9.22848911e-01, 3.98261697e-01, 9.19621888e-01],
         [2.30784127e-01, 8.09647413e-01, 7.66486865e-01],
         [4.11897173e-01, 8.68467383e-01, 4.51581296e-02]],

        [[7.51038214e-01, 8.75414337e-02, 1.72962400e-01],
         [1.41097298e-01, 8.73415615e-01, 2.80424911e-01],
         [3.65669639e-01, 2.66161778e-01, 6.26254438e-04],
         [4.50419685e-01, 9.97067728e-01, 7.47485101e-01],
         [9.26512183e-02, 1.98589241e-01, 8.83847730e-02]],

        [[9.61751339e-01, 4.63742555e-02, 5.50842712e-01],
         [5.02166927e-01, 5.46547708e-01, 5.714755

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 51ms/step


2023-10-22 17:35:57.079358: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[ 0.31790018, -0.3953592 ],
         [ 0.13942084,  0.00890624],
         [ 0.00868316, -0.58482945]],

        [[ 0.30897242,  0.19853407],
         [ 0.700971  ,  0.08636481],
         [ 0.02942782, -0.5222873 ]],

        [[-0.13509262, -0.82825524],
         [-0.20917095,  0.00248058],
         [ 0.3431852 , -0.49717993]]]], dtype=float32)

In [7]:
X_in = (X*1000).round().astype(int)
weights = (model.weights[0].numpy()*1000).round().astype(int)

In [8]:
new_model = model
new_model.weights[0].assign(weights)
res = new_model.predict(X_in).round().astype(int)
out = res // 1000
remainder = res % 1000
out

1/1 [==============================] - 0s 29ms/step


array([[[[ 317, -395],
         [ 139,    8],
         [   8, -585]],

        [[ 310,  198],
         [ 701,   87],
         [  30, -523]],

        [[-135, -828],
         [-209,    3],
         [ 343, -498]]]])

In [9]:
in_json = {
    "in": X_in.flatten().tolist(),
    "weights": weights.flatten().tolist(),
    "bias": [0,0],
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [10]:
import json

In [11]:
with open("conv2D_input.json", "w") as f:
    json.dump(in_json, f)

In [12]:
inputs = Input(shape=(10,10,3))
x = Conv2D(2, 4, 3)(inputs)
model = Model(inputs, x)

In [13]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 conv2d_1 (Conv2D)           (None, 3, 3, 2)           98        
                                                                 
Total params: 98
Trainable params: 98
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.weights

[<tf.Variable 'conv2d_1/kernel:0' shape=(4, 4, 3, 2) dtype=float32, numpy=
 array([[[[ 0.15086025,  0.11460546],
          [-0.09543172, -0.05872606],
          [-0.12650312, -0.08248164]],
 
         [[-0.01265591,  0.21442032],
          [ 0.04394221, -0.17748183],
          [-0.25020188, -0.05316879]],
 
         [[ 0.11280355,  0.03786325],
          [ 0.08235529,  0.18647239],
          [ 0.18573561,  0.20067975]],
 
         [[-0.2714741 ,  0.11000285],
          [-0.07244399,  0.16133094],
          [-0.17847215,  0.07812056]]],
 
 
        [[[-0.1025826 ,  0.19663644],
          [-0.13668874, -0.01021376],
          [-0.24935608,  0.01381683]],
 
         [[ 0.11925364, -0.14257991],
          [ 0.08069637, -0.09250376],
          [ 0.03255108,  0.25512505]],
 
         [[-0.11158666,  0.1918337 ],
          [-0.00137502, -0.20034355],
          [-0.20899183, -0.22188228]],
 
         [[ 0.09096184, -0.0838265 ],
          [ 0.11686403,  0.1847161 ],
          [-0.26108745, -0.

In [15]:
X = np.random.rand(1,10,10,3)
X

array([[[[8.86353244e-01, 7.16198811e-01, 5.34885929e-01],
         [4.89940171e-01, 4.49657666e-01, 7.70125754e-01],
         [7.39937599e-01, 8.38363891e-01, 4.82990935e-01],
         [7.48079656e-01, 9.30439413e-01, 9.21352234e-01],
         [9.26769554e-01, 4.67425515e-01, 8.24513898e-01],
         [4.53804427e-01, 7.81078642e-01, 7.43187256e-01],
         [9.45176473e-01, 3.78270789e-01, 5.14366396e-01],
         [2.55115386e-01, 6.43064000e-01, 7.27743312e-01],
         [1.53936825e-01, 4.97791146e-01, 3.34049407e-01],
         [1.83834750e-01, 9.01534434e-01, 5.52853567e-01]],

        [[7.69253645e-01, 5.14668600e-01, 4.56713072e-01],
         [2.03267014e-01, 4.57806967e-01, 8.07797840e-02],
         [7.87210383e-02, 5.54426523e-01, 8.34848492e-01],
         [6.66036647e-01, 1.67766299e-01, 3.02426915e-01],
         [5.73856152e-01, 7.63545791e-01, 9.65111915e-01],
         [8.09801082e-01, 8.82932830e-01, 2.45252276e-02],
         [7.61472123e-01, 8.90323740e-01, 5.65637000e-

In [16]:
y = model.predict(X)
y

1/1 [==============================] - 0s 37ms/step


array([[[[-2.0444643 ,  0.04492658],
         [-1.7182257 ,  0.45661664],
         [-1.5283277 , -0.14555633]],

        [[-1.1088883 ,  0.4977825 ],
         [-1.7310873 , -0.0083015 ],
         [-1.5744288 ,  0.43289617]],

        [[-1.4029372 ,  0.6158208 ],
         [-1.8923826 ,  0.53400177],
         [-1.2505736 ,  0.82813364]]]], dtype=float32)

In [17]:
X_in = (X*1000).round().astype(int)
weights = (model.weights[0].numpy()*1000).round().astype(int)

In [18]:
new_model = model
new_model.weights[0].assign(weights)
res = new_model.predict(X_in).round().astype(int)
out = res // 1000
remainder = res % 1000
out

1/1 [==============================] - 0s 32ms/step


array([[[[-2043,    46],
         [-1717,   456],
         [-1528,  -144]],

        [[-1108,   498],
         [-1729,    -6],
         [-1574,   435]],

        [[-1403,   617],
         [-1892,   535],
         [-1250,   828]]]])

In [19]:
in_json = {
    "in": X_in.flatten().tolist(),
    "weights": weights.flatten().tolist(),
    "bias": [0,0],
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [20]:
with open("conv2D_stride_input.json", "w") as f:
    json.dump(in_json, f)