In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
conv2d (Conv2D)              (None, 3, 3, 2)           56        
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[ 0.00532213,  0.01806945],
          [-0.08018309,  0.13749993],
          [ 0.15713441,  0.04590532]],
 
         [[-0.10268021, -0.08381525],
          [ 0.00625068, -0.06617117],
          [-0.27868283,  0.15321946]],
 
         [[ 0.07455695,  0.15443742],
          [-0.10475847,  0.20064372],
          [-0.16788703,  0.28371173]]],
 
 
        [[[-0.18503287,  0.35247225],
          [-0.09500805,  0.24461341],
          [ 0.1247969 ,  0.30034906]],
 
         [[-0.10620868, -0.08424199],
          [ 0.03252754, -0.10200378],
          [ 0.01500395, -0.10338616]],
 
         [[ 0.12937981,  0.00390726],
          [-0.3165103 , -0.09928879],
          [-0.10858417, -0.07013884]]],
 
 
        [[[-0.1355082 , -0.01285639],
          [ 0.13220546, -0.1390203 ],
          [ 0.34691995, -0.07693747]],
 
         [[ 0.18586475,  0.1771779 ],
          [ 0.2107383 ,  0.20343399],
          [ 0.26660055, -0

In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.07706963, 0.89463434, 0.1897133 ],
         [0.30366886, 0.19307375, 0.6178037 ],
         [0.88041068, 0.50786565, 0.51687829],
         [0.63407746, 0.61299695, 0.43654402],
         [0.85343424, 0.14670523, 0.93538307]],

        [[0.62738085, 0.96599414, 0.54225448],
         [0.97695477, 0.51189504, 0.64659635],
         [0.14987877, 0.76167303, 0.88906146],
         [0.69694305, 0.52868868, 0.15631565],
         [0.26004293, 0.16167052, 0.54175091]],

        [[0.06935492, 0.48436401, 0.89326109],
         [0.11489624, 0.17011633, 0.57831794],
         [0.41737643, 0.20459155, 0.355945  ],
         [0.18405935, 0.36680556, 0.44706071],
         [0.61416318, 0.71028094, 0.72964778]],

        [[0.14665591, 0.49169179, 0.34747557],
         [0.85826504, 0.33210524, 0.18229433],
         [0.82389036, 0.83632002, 0.14352168],
         [0.5986361 , 0.78300801, 0.92352137],
         [0.32828077, 0.46306303, 0.02765627]],

        [[0.75507086, 0.95771695, 0.97896974],
     

In [6]:
y = model.predict(X)
y

array([[[[-0.47057757,  0.87940997],
         [-0.22883852,  0.9216037 ],
         [-0.44013992,  1.0718222 ]],

        [[-0.37989584,  1.1078516 ],
         [-0.4495669 ,  1.0322194 ],
         [ 0.01791049,  0.49668407]],

        [[-0.16616501,  0.42594796],
         [-0.79061836,  0.731256  ],
         [-0.39701813,  1.2579358 ]]]], dtype=float32)

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": [0,0]
}

In [8]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("conv2D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv2D_output.json", "w") as f:
    json.dump(out_json, f)