In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = Conv2D(2, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
conv2d (Conv2D)              (None, 3, 3, 2)           56        
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[ 0.00532213,  0.01806945],
          [-0.08018309,  0.13749993],
          [ 0.15713441,  0.04590532]],
 
         [[-0.10268021, -0.08381525],
          [ 0.00625068, -0.06617117],
          [-0.27868283,  0.15321946]],
 
         [[ 0.07455695,  0.15443742],
          [-0.10475847,  0.20064372],
          [-0.16788703,  0.28371173]]],
 
 
        [[[-0.18503287,  0.35247225],
          [-0.09500805,  0.24461341],
          [ 0.1247969 ,  0.30034906]],
 
         [[-0.10620868, -0.08424199],
          [ 0.03252754, -0.10200378],
          [ 0.01500395, -0.10338616]],
 
         [[ 0.12937981,  0.00390726],
          [-0.3165103 , -0.09928879],
          [-0.10858417, -0.07013884]]],
 
 
        [[[-0.1355082 , -0.01285639],
          [ 0.13220546, -0.1390203 ],
          [ 0.34691995, -0.07693747]],
 
         [[ 0.18586475,  0.1771779 ],
          [ 0.2107383 ,  0.20343399],
          [ 0.26660055, -0

In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.07706963, 0.89463434, 0.1897133 ],
         [0.30366886, 0.19307375, 0.6178037 ],
         [0.88041068, 0.50786565, 0.51687829],
         [0.63407746, 0.61299695, 0.43654402],
         [0.85343424, 0.14670523, 0.93538307]],

        [[0.62738085, 0.96599414, 0.54225448],
         [0.97695477, 0.51189504, 0.64659635],
         [0.14987877, 0.76167303, 0.88906146],
         [0.69694305, 0.52868868, 0.15631565],
         [0.26004293, 0.16167052, 0.54175091]],

        [[0.06935492, 0.48436401, 0.89326109],
         [0.11489624, 0.17011633, 0.57831794],
         [0.41737643, 0.20459155, 0.355945  ],
         [0.18405935, 0.36680556, 0.44706071],
         [0.61416318, 0.71028094, 0.72964778]],

        [[0.14665591, 0.49169179, 0.34747557],
         [0.85826504, 0.33210524, 0.18229433],
         [0.82389036, 0.83632002, 0.14352168],
         [0.5986361 , 0.78300801, 0.92352137],
         [0.32828077, 0.46306303, 0.02765627]],

        [[0.75507086, 0.95771695, 0.97896974],
     

In [6]:
y = model.predict(X)
y

array([[[[-0.47057757,  0.87940997],
         [-0.22883852,  0.9216037 ],
         [-0.44013992,  1.0718222 ]],

        [[-0.37989584,  1.1078516 ],
         [-0.4495669 ,  1.0322194 ],
         [ 0.01791049,  0.49668407]],

        [[-0.16616501,  0.42594796],
         [-0.79061836,  0.731256  ],
         [-0.39701813,  1.2579358 ]]]], dtype=float32)

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": [0,0]
}

In [8]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("conv2D_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv2D_output.json", "w") as f:
    json.dump(out_json, f)

In [2]:
inputs = Input(shape=(10,10,3))
x = Conv2D(2, 4, 3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 10, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 3, 3, 2)           98        
Total params: 98
Trainable params: 98
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(4, 4, 3, 2) dtype=float32, numpy=
 array([[[[ 9.01020467e-02,  6.39823377e-02],
          [ 1.72438890e-01,  1.19038552e-01],
          [-2.31111139e-01,  7.65160322e-02]],
 
         [[ 5.60960472e-02,  8.70717168e-02],
          [ 1.09150052e-01, -1.31718382e-01],
          [ 7.23880231e-02, -4.93483245e-02]],
 
         [[-1.44102752e-01, -2.04105571e-01],
          [-1.85530186e-01, -2.36467183e-01],
          [-1.34880558e-01, -1.99714184e-01]],
 
         [[-3.83580476e-02,  2.45451868e-01],
          [ 9.63985324e-02,  1.29009217e-01],
          [ 1.38856411e-01, -6.06727898e-02]]],
 
 
        [[[-1.54422879e-01, -1.56738907e-01],
          [ 1.74920231e-01,  2.34346807e-01],
          [-9.43229645e-02,  1.37158900e-01]],
 
         [[ 1.38553441e-01, -5.22587299e-02],
          [ 1.23419642e-01,  3.11977565e-02],
          [-2.27711692e-01,  1.64391518e-01]],
 
         [[ 1.41024947e-01,  1.13755465e-04],
          [ 1.99488789e-01,  2.5

In [5]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.97251485, 0.45513694, 0.02700021],
         [0.77939851, 0.57285348, 0.64336143],
         [0.7910932 , 0.68158499, 0.55903757],
         [0.19978621, 0.16401386, 0.1178243 ],
         [0.26202894, 0.73739062, 0.41515085],
         [0.91602252, 0.1889969 , 0.86812371],
         [0.90520645, 0.88021945, 0.56918999],
         [0.1576814 , 0.66244825, 0.76843253],
         [0.91151503, 0.18348028, 0.83457797],
         [0.54744986, 0.6653615 , 0.88219377]],

        [[0.75996691, 0.51053919, 0.93055488],
         [0.91144281, 0.56385737, 0.15222672],
         [0.03655235, 0.37340661, 0.10463077],
         [0.44692914, 0.54256831, 0.84009866],
         [0.79509769, 0.09059503, 0.35705721],
         [0.51836358, 0.56141664, 0.58831904],
         [0.84739405, 0.63802925, 0.66017923],
         [0.92534248, 0.63225917, 0.7473312 ],
         [0.73096606, 0.40520727, 0.97955684],
         [0.63831414, 0.89495898, 0.32695978]],

        [[0.71829301, 0.46062667, 0.71811823],
         

In [6]:
y = model.predict(X)
y

array([[[[0.60406584, 0.04963745],
         [0.8254909 , 0.59482723],
         [0.93028533, 0.22805347]],

        [[1.2823461 , 0.5949404 ],
         [0.897624  , 0.3798192 ],
         [1.1588949 , 0.44623226]],

        [[0.5934084 , 0.06460603],
         [1.2609756 , 0.25182724],
         [0.5040486 , 0.6587203 ]]]], dtype=float32)

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "bias": [0,0]
}

In [8]:
out_json = {
    "out": (y*1000000).round().astype(int).flatten().tolist()
}

In [10]:
with open("conv2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("conv2D_stride_output.json", "w") as f:
    json.dump(out_json, f)