In [1]:
from tensorflow.keras.layers import Input, Conv2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = Conv2D(2, 3, padding="same")(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 conv2d (Conv2D)             (None, 5, 5, 2)           56        
                                                                 
Total params: 56
Trainable params: 56
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv2d/kernel:0' shape=(3, 3, 3, 2) dtype=float32, numpy=
 array([[[[-0.22388998,  0.18217945],
          [-0.31254017,  0.13933456],
          [-0.14491144,  0.01168695]],
 
         [[-0.18442051,  0.16668755],
          [-0.15052032, -0.1277689 ],
          [-0.17660408, -0.25577286]],
 
         [[-0.3273484 ,  0.06551823],
          [ 0.02335805,  0.30579627],
          [ 0.05012453,  0.05196694]]],
 
 
        [[[-0.15296353, -0.28653675],
          [ 0.31760007,  0.27596015],
          [ 0.06140944,  0.28459537]],
 
         [[-0.271937  ,  0.3022167 ],
          [ 0.34724104,  0.3508402 ],
          [-0.26121286, -0.10477605]],
 
         [[ 0.18311954,  0.15618789],
          [ 0.21608043,  0.07763481],
          [-0.17695144, -0.29946056]]],
 
 
        [[[ 0.2186423 ,  0.2389586 ],
          [-0.2976641 , -0.30056122],
          [-0.35727727, -0.3631401 ]],
 
         [[-0.04230955, -0.15279846],
          [ 0.06897295, -0.08147189],
          [-0.30367035,  0

In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.57357832, 0.79689708, 0.54481385],
         [0.95096481, 0.06302099, 0.53424686],
         [0.14555327, 0.16801407, 0.91837743],
         [0.14042694, 0.26466775, 0.0754911 ],
         [0.19354151, 0.89796698, 0.18080666]],

        [[0.84893864, 0.94689375, 0.76889793],
         [0.91280106, 0.81211903, 0.50614878],
         [0.72629997, 0.09620774, 0.05074255],
         [0.30178926, 0.4854865 , 0.46486629],
         [0.87558861, 0.93289185, 0.33965317]],

        [[0.23726595, 0.09253935, 0.08598877],
         [0.24484708, 0.00811252, 0.23642884],
         [0.65975124, 0.63633904, 0.82507772],
         [0.53100731, 0.72433054, 0.66373751],
         [0.43916625, 0.74347257, 0.6772263 ]],

        [[0.87412193, 0.53853422, 0.34772628],
         [0.7738511 , 0.97565729, 0.94426861],
         [0.21537231, 0.65774623, 0.89405016],
         [0.7411118 , 0.68792609, 0.3272619 ],
         [0.44887834, 0.924486  , 0.48269841]],

        [[0.13952337, 0.79659803, 0.97603335],
     

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 51ms/step


2024-02-04 01:25:53.532541: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[-0.7382064 , -0.17332056],
         [-1.034698  , -0.43408912],
         [-0.83073455, -0.6865788 ],
         [-0.28542495,  0.0770359 ],
         [-0.04129319,  0.02877748]],

        [[-0.60671365,  0.38846642],
         [-1.1027374 ,  0.71167284],
         [-1.2792461 , -0.10405768],
         [-1.1375024 , -0.28573734],
         [-0.7037988 ,  0.3554073 ]],

        [[-1.5469512 , -0.50975496],
         [-2.0071907 , -0.25512454],
         [-1.9879558 ,  0.09278526],
         [-1.5013543 , -0.14000578],
         [-0.7585893 ,  0.43752092]],

        [[-0.7614179 ,  0.09177176],
         [-1.688165  , -0.25309083],
         [-0.8684121 ,  0.42702955],
         [-1.6322078 ,  0.3133433 ],
         [-1.1236074 ,  0.2770568 ]],

        [[-0.54382604,  0.415062  ],
         [-1.0068984 ,  0.6469521 ],
         [-1.3391564 ,  0.42430705],
         [-0.6338484 ,  0.63813394],
         [-0.9111921 ,  0.5726407 ]]]], dtype=float32)

In [7]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(5)] for i in range(5)]
weights = [[[[int(model.weights[0].numpy()[i][j][k][l]*1e36) for l in range(2)] for k in range(3)] for j in range(3)] for i in range(3)]
bias = [int(model.weights[1].numpy()[i]*1e72) for i in range(2)]

In [8]:
def Conv2DInt(nRows, nCols, nChannels, nFilters, kernelSize, strides, n, input, weights, bias):
    out = [[[0 for _ in range(nFilters)] for _ in range((nCols - kernelSize)//strides + 1)] for _ in range((nRows - kernelSize)//strides + 1)]
    remainder = [[[None for _ in range(nFilters)] for _ in range((nCols - kernelSize)//strides + 1)] for _ in range((nRows - kernelSize)//strides + 1)]
    for i in range((nRows - kernelSize)//strides + 1):
        for j in range((nCols - kernelSize)//strides + 1):
            for m in range(nFilters):
                for k in range(nChannels):
                    for x in range(kernelSize):
                        for y in range(kernelSize):
                            out[i][j][m] += int(input[i*strides+x][j*strides+y][k])*int(weights[x][y][k][m])
                out[i][j][m] += int(bias[m])
                remainder[i][j][m] = str(out[i][j][m] % n)
                out[i][j][m] = str(out[i][j][m] // n)
    return out, remainder

In [9]:
def Conv2DsameInt(nRows, nCols, nChannels, nFilters, kernelSize, strides, n, input, weights, bias):
    if nRows % strides == 0:
        rowPadding = max(kernelSize - strides, 0)
    else:
        rowPadding = max(kernelSize - nRows % strides, 0)
    if nCols % strides == 0:
        colPadding = max(kernelSize - strides, 0)
    else:
        colPadding = max(kernelSize - nCols % strides, 0)
    
    _input = [[[0 for _ in range(nChannels)] for _ in range(nCols + colPadding)] for _ in range(nRows + rowPadding)]

    for i in range(nRows):
        for j in range(nCols):
            for k in range(nChannels):
                _input[i+rowPadding//2][j+colPadding//2][k] = input[i][j][k]
    
    out, remainder = Conv2DInt(nRows + rowPadding, nCols + colPadding, nChannels, nFilters, kernelSize, strides, n, _input, weights, bias)
    return out, remainder

In [10]:
out, remainder = Conv2DsameInt(5, 5, 3, 2, 3, 1, 10**36, X_in, weights, bias)
out, remainder

([[['-738206413373029545006965393527124494',
    '-173320559228639935825945330543413025'],
   ['-1034698083357167138897799627355946893',
    '-434089078628623353676508551211157060'],
   ['-830734559502817036444813835112148949',
    '-686578771866623630758607927275546159'],
   ['-285424960673894669036410085848276078',
    '77035899885765173133597720803628368'],
   ['-41293201078409047199874417933080796',
    '28777494655737863382696013669386951']],
  [['-606713676308333020774846244444307246',
    '388466467207809267549922375129065936'],
   ['-1102737485952039787132334772316590877',
    '711672842283067459049106389539428334'],
   ['-1279246107747464951673577203827572661',
    '-104057682619248993879676863654015882'],
   ['-1137502411882990109129978808062308003',
    '-285737283216816113761016693211231047'],
   ['-703798773277911056745141956845225462',
    '355407338114374779173330249858051758']],
  [['-1546951103062535866431703941066730304',
    '-509754977574520651977576289008629976'],


In [11]:
in_json = {
    "in": X_in,
    "weights": weights,
    "bias": bias,
    "out": out,
    "remainder": remainder
}

In [12]:
import json

In [13]:
with open("conv2Dsame_input.json", "w") as f:
    json.dump(in_json, f)

In [14]:
inputs = Input(shape=(10,10,3))
x = Conv2D(2, 4, 3, padding="same")(inputs)
model = Model(inputs, x)

In [15]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 conv2d_1 (Conv2D)           (None, 4, 4, 2)           98        
                                                                 
Total params: 98
Trainable params: 98
Non-trainable params: 0
_________________________________________________________________


In [16]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.15917131, 0.77313235, 0.70732347],
         [0.85210236, 0.77747055, 0.9126757 ],
         [0.93479056, 0.819227  , 0.70156189],
         [0.79143794, 0.87801591, 0.82904976],
         [0.68619248, 0.52939185, 0.9781374 ],
         [0.60719573, 0.89925314, 0.76945961],
         [0.87552557, 0.90534932, 0.87889951],
         [0.3906682 , 0.95580616, 0.31789736],
         [0.76477277, 0.81754225, 0.69839668],
         [0.83091809, 0.08929047, 0.41690024]],

        [[0.02156404, 0.1248342 , 0.10101914],
         [0.89801399, 0.26753341, 0.07441736],
         [0.02208311, 0.63957509, 0.89741475],
         [0.34053784, 0.26694358, 0.75715605],
         [0.53780638, 0.65565436, 0.91504456],
         [0.25938895, 0.93164592, 0.89508771],
         [0.59673249, 0.83579125, 0.43718874],
         [0.15159799, 0.74559263, 0.75890839],
         [0.14960964, 0.72981249, 0.3738258 ],
         [0.77609438, 0.61152145, 0.26743727]],

        [[0.86386277, 0.08854458, 0.1881181 ],
         

In [17]:
y = model.predict(X)
y

1/1 [==============================] - 0s 28ms/step


array([[[[-0.811051  , -1.4721096 ],
         [-0.52853954, -0.47991082],
         [-0.8595364 , -0.6705183 ],
         [-0.07767564, -0.1320289 ]],

        [[-0.9737919 , -0.5298958 ],
         [-1.0687585 , -0.33069813],
         [-0.96858287, -0.61539143],
         [-0.34952405, -0.3947128 ]],

        [[-1.1950083 , -0.39145365],
         [-1.0355395 ,  0.37544912],
         [-0.46857417, -0.46149284],
         [-0.1579878 , -0.14529735]],

        [[-0.7178327 , -0.6407934 ],
         [-0.81823504, -0.48652953],
         [-0.48897535, -0.5935499 ],
         [-0.0888171 , -0.18892495]]]], dtype=float32)

In [18]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(10)] for i in range(10)]
weights = [[[[int(model.weights[0].numpy()[i][j][k][l]*1e36) for l in range(2)] for k in range(3)] for j in range(4)] for i in range(4)]
bias = [int(model.weights[1].numpy()[i]*1e72) for i in range(2)]

In [19]:
out, remainder = Conv2DsameInt(10, 10, 3, 2, 4, 3, 10**36, X_in, weights, bias)
out, remainder

([[['-811051029307312151898080091259013408',
    '-1472109697883872855085104222700990006'],
   ['-528539552873451841296887387802887946',
    '-479910753097361964472240108640655029'],
   ['-859536355090285293603582494722226955',
    '-670518221637687591501448018045711492'],
   ['-77675673238639598916850751879067826',
    '-132028915984577730731287477184728367']],
  [['-973791923027617402137438972479106354',
    '-529895757470201620182206632643141082'],
   ['-1068758558577939368141318995900977305',
    '-330698196577790148366400564712521445'],
   ['-968582927650604267027127767242160672',
    '-615391447297339813950840270560399175'],
   ['-349524047948521414307381813385449474',
    '-394712802987869376369174007174918150']],
  [['-1195008336948108945640918772722080227',
    '-391453675833271485890705066425298906'],
   ['-1035539474474336745928350434338370235',
    '375449144451453718974060701074107917'],
   ['-468574096206261610672918401549766744',
    '-46149288173180494442241939590496408

In [20]:
in_json = {
    "in": X_in,
    "weights": weights,
    "bias": bias,
    "out": out,
    "remainder": remainder
}

In [21]:
with open("conv2Dsame_stride_input.json", "w") as f:
    json.dump(in_json, f)