In [1]:
from tensorflow.keras.layers import Input, Conv1D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(20,3))
x = Conv1D(2,4,3)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 20, 3)]           0         
                                                                 
 conv1d (Conv1D)             (None, 6, 2)              26        
                                                                 
Total params: 26
Trainable params: 26
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'conv1d/kernel:0' shape=(4, 3, 2) dtype=float32, numpy=
 array([[[-0.02601326, -0.3301772 ],
         [-0.43577537,  0.15717334],
         [-0.4259557 , -0.33559367]],
 
        [[ 0.42399222,  0.37510973],
         [ 0.54508114,  0.4104665 ],
         [-0.19787505, -0.22848248]],
 
        [[ 0.1666612 ,  0.26736772],
         [ 0.27143848, -0.06004363],
         [-0.34151512, -0.12771094]],
 
        [[-0.36906815,  0.25710082],
         [-0.3379731 ,  0.32230026],
         [ 0.4884795 , -0.09015676]]], dtype=float32)>,
 <tf.Variable 'conv1d/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>]

In [5]:
X = np.random.rand(1,20,3)
X

array([[[0.6559202 , 0.56228804, 0.02962599],
        [0.76994812, 0.47743693, 0.5572069 ],
        [0.19927724, 0.96605039, 0.34841999],
        [0.09700514, 0.46599331, 0.82709989],
        [0.31069412, 0.15947317, 0.57927911],
        [0.12190963, 0.03995945, 0.06157934],
        [0.16758128, 0.04181142, 0.82223711],
        [0.0339618 , 0.07949938, 0.4784424 ],
        [0.36242002, 0.86249361, 0.81787561],
        [0.76752837, 0.14955845, 0.19923647],
        [0.75422543, 0.67576628, 0.15690422],
        [0.01331625, 0.21074644, 0.65650254],
        [0.40707105, 0.56040591, 0.28207027],
        [0.97407273, 0.62589764, 0.13727775],
        [0.89228633, 0.74312463, 0.03756628],
        [0.44731329, 0.90640783, 0.9485793 ],
        [0.23960207, 0.34310035, 0.84625871],
        [0.41156359, 0.7461549 , 0.90558762],
        [0.95574097, 0.12621598, 0.96342998],
        [0.65423917, 0.39415099, 0.51843145]]])

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 67ms/step


2023-10-22 17:26:08.709261: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[ 0.58889425,  0.27067867],
        [-0.11806718, -0.18194711],
        [-0.6310506 , -0.22040904],
        [ 0.12044493,  0.39458114],
        [ 0.68157434,  0.96071315],
        [-0.6524461 , -0.13708869]]], dtype=float32)

In [7]:
X_in = (X*1000).round().astype(int)
weights = (model.weights[0].numpy()*1000).round().astype(int)
bias = np.zeros(model.weights[1].numpy().shape).astype(int)
X_in, weights, bias

(array([[[656, 562,  30],
         [770, 477, 557],
         [199, 966, 348],
         [ 97, 466, 827],
         [311, 159, 579],
         [122,  40,  62],
         [168,  42, 822],
         [ 34,  79, 478],
         [362, 862, 818],
         [768, 150, 199],
         [754, 676, 157],
         [ 13, 211, 657],
         [407, 560, 282],
         [974, 626, 137],
         [892, 743,  38],
         [447, 906, 949],
         [240, 343, 846],
         [412, 746, 906],
         [956, 126, 963],
         [654, 394, 518]]]),
 array([[[ -26, -330],
         [-436,  157],
         [-426, -336]],
 
        [[ 424,  375],
         [ 545,  410],
         [-198, -228]],
 
        [[ 167,  267],
         [ 271,  -60],
         [-342, -128]],
 
        [[-369,  257],
         [-338,  322],
         [ 488,  -90]]]),
 array([0, 0]))

In [8]:
new_model = model
new_model.weights[0].assign(weights)
res = new_model.predict(X_in).round().astype(int)
out = res // 1000
remainder = res % 1000
out, remainder

1/1 [==============================] - 0s 40ms/step


(array([[[ 587,  270],
         [-120, -182],
         [-633, -221],
         [ 119,  393],
         [ 681,  959],
         [-655, -138]]]),
 array([[[569, 178],
         [835,  41],
         [295, 114],
         [699, 614],
         [408, 453],
         [985, 480]]]))

In [9]:
in_json = {
    "in": X_in.flatten().tolist(),
    "weights": weights.flatten().tolist(),
    "bias": bias.tolist(),
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [10]:
import json

In [11]:
with open("conv1D_input.json", "w") as f:
    json.dump(in_json, f)