In [1]:
from tensorflow.keras.layers import Input, GlobalAveragePooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
out = GlobalAveragePooling2D()(inputs)
model = Model(inputs, out)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 global_average_pooling2d (G  (None, 3)                0         
 lobalAveragePooling2D)                                          
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = (np.random.rand(1,5,5,3)*1000).round().astype(int)
X

array([[[[413, 249, 210],
         [220, 368, 195],
         [489, 948, 924],
         [545, 156, 250],
         [871, 127,  54]],

        [[432, 335, 655],
         [708, 991, 991],
         [511, 499, 746],
         [ 67, 815, 275],
         [ 78, 848, 271]],

        [[ 72, 180, 726],
         [536, 647, 504],
         [177, 712, 839],
         [384, 811, 484],
         [830, 362, 293]],

        [[419,  39, 671],
         [ 82, 698, 417],
         [363, 701, 752],
         [353, 356,  40],
         [471, 959, 115]],

        [[ 82, 961, 835],
         [650, 342, 178],
         [292, 583, 669],
         [535, 818, 948],
         [684, 195, 468]]]])

In [5]:
y = model.predict(X)
y

1/1 [==============================] - 0s 82ms/step


2023-10-22 19:04:40.749218: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[410.56, 548.  , 500.4 ]], dtype=float32)

In [6]:
out = np.floor(y).astype(int)
out

array([[410, 548, 500]])

In [7]:
remainder = (y * 25 - out * 25).round().astype(int)
remainder

array([[14,  0, 10]])

In [8]:
in_json = {
    "in": X.flatten().tolist(),
    "out": out.flatten().tolist(),
    "remainder": remainder.flatten().tolist()
}

In [9]:
import json

In [10]:
with open("globalAveragePooling2D_input.json", "w") as f:
    json.dump(in_json, f)