In [1]:
p = 21888242871839275222246405745257275088548364400416034343698204186575808495617

In [2]:
from tensorflow.keras.layers import Input, MaxPooling2D
from tensorflow.keras import Model
import numpy as np

In [3]:
inputs = Input(shape=(5,5,3))
x = MaxPooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 2, 2, 3)          0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [5]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.44076837, 0.4645178 , 0.88532658],
         [0.98571178, 0.36091035, 0.37878294],
         [0.09039054, 0.43555648, 0.70723494],
         [0.75087575, 0.46161156, 0.27621923],
         [0.3658674 , 0.76096207, 0.85368763]],

        [[0.53353854, 0.18599507, 0.85547589],
         [0.83705565, 0.3310797 , 0.42121576],
         [0.97948862, 0.58870474, 0.022469  ],
         [0.40446888, 0.15924946, 0.39474075],
         [0.39336331, 0.83113873, 0.58711273]],

        [[0.00324599, 0.84351736, 0.65574229],
         [0.00423293, 0.09477659, 0.85111496],
         [0.84792575, 0.32417744, 0.52031854],
         [0.78577668, 0.63963473, 0.66767045],
         [0.6838523 , 0.40963437, 0.296101  ]],

        [[0.25513283, 0.21434056, 0.139309  ],
         [0.61281984, 0.77039643, 0.3830965 ],
         [0.52747206, 0.60847264, 0.60792949],
         [0.63030064, 0.5966706 , 0.05825615],
         [0.78633397, 0.4404418 , 0.30296519]],

        [[0.4233433 , 0.2882031 , 0.85232675],
     

In [6]:
y = model.predict(X)
y

1/1 [==============================] - 0s 29ms/step


2023-10-23 21:44:15.505331: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[0.98571175, 0.4645178 , 0.88532656],
         [0.9794886 , 0.58870476, 0.7072349 ]],

        [[0.61281985, 0.84351736, 0.851115  ],
         [0.8479257 , 0.6396347 , 0.6676704 ]]]], dtype=float32)

In [7]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(5)] for i in range(5)]

In [8]:
def MaxPooling2DInt(nRows, nCols, nChannels, poolSize, strides, input):
    Input = [[[str(input[i][j][k] % p) for k in range(nChannels)] for j in range(nCols)] for i in range(nRows)]
    out = [[[str(max(input[i*strides + x][j*strides + y][k] for x in range(poolSize) for y in range(poolSize)) % p) for k in range(nChannels)] for j in range((nCols - poolSize) // strides + 1)] for i in range((nRows - poolSize) // strides + 1)]
    return Input, out

In [9]:
X_in, out = MaxPooling2DInt(5, 5, 3, 2, 2, X_in)
out

[[['985711776216457240221750775571808256',
   '464517795839652376609037137683152896',
   '885326582306963556558255153072832512'],
  ['979488619923621857462245439242764288',
   '588704741840418336217153490575687680',
   '707234940167889112717525758819434496']],
 [['612819836329411865644509177766215680',
   '843517362609097245279278883187720192',
   '851114962252709222552843081379479552'],
  ['847925751912674500468804749306626048',
   '639634733901388366288661852182282240',
   '667670451847854954465177838892875776']]]

In [10]:
in_json = {
    "in": X_in,
    "out": out
}

In [11]:
import json

In [12]:
with open("maxPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [13]:
inputs = Input(shape=(10,10,3))
x = MaxPooling2D(pool_size=2, strides=3)(inputs)
model = Model(inputs, x)

In [14]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 3, 3, 3)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [15]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.9790171 , 0.49837833, 0.23951505],
         [0.85478487, 0.10183569, 0.57204256],
         [0.12906496, 0.12259599, 0.61308313],
         [0.68956844, 0.27468499, 0.73800473],
         [0.97031435, 0.65275678, 0.57039273],
         [0.48422669, 0.62184484, 0.12322611],
         [0.45518299, 0.70342415, 0.77375435],
         [0.1334539 , 0.78283045, 0.48137776],
         [0.97002355, 0.70346344, 0.04099013],
         [0.34556716, 0.30939804, 0.12870492]],

        [[0.55049916, 0.15188193, 0.514953  ],
         [0.07403779, 0.906408  , 0.20947497],
         [0.57003003, 0.93417836, 0.09306473],
         [0.17917856, 0.67291796, 0.4088607 ],
         [0.10408118, 0.55822855, 0.62854813],
         [0.20925919, 0.68269696, 0.60650138],
         [0.94999975, 0.12429107, 0.41003125],
         [0.16150869, 0.35470003, 0.54676562],
         [0.14792857, 0.78346031, 0.25734593],
         [0.89233997, 0.28742825, 0.13791151]],

        [[0.79274313, 0.99061523, 0.68711779],
         

In [16]:
y = model.predict(X)
y

1/1 [==============================] - 0s 21ms/step


array([[[[0.9790171 , 0.906408  , 0.5720426 ],
         [0.9703143 , 0.67291796, 0.73800474],
         [0.94999975, 0.7828305 , 0.77375436]],

        [[0.5541662 , 0.901849  , 0.9279116 ],
         [0.7338952 , 0.9820815 , 0.60164225],
         [0.7200732 , 0.46328673, 0.98273623]],

        [[0.660698  , 0.9045992 , 0.86337173],
         [0.6887103 , 0.86998105, 0.7918348 ],
         [0.9153599 , 0.76506644, 0.89466846]]]], dtype=float32)

In [17]:
X_in = [[[int(X[0][i][j][k]*1e36) for k in range(3)] for j in range(10)] for i in range(10)]

In [18]:
X_in, out = MaxPooling2DInt(10, 10, 3, 2, 3, X_in)
out

[[['979017099491110018942067312821272576',
   '906408000806632452114797174150135808',
   '572042560577051270101001688850628608'],
  ['970314350513558277989324779994218496',
   '672917960272193945175567190387064832',
   '738004729474624730341896972922781696'],
  ['949999745668024165489517038806237184',
   '782830451141896167400921576545189888',
   '773754352982266439136539456512720896']],
 [['554166181126147404440246990770536448',
   '901848991352918850169033731149398016',
   '927911571088135929200009259356520448'],
  ['733895199634136636354978553303924736',
   '982081449688638090663868389740511232',
   '601642265832659125360941789945528320'],
  ['720073208604618054954869080641765376',
   '463286712794445136678401315688153088',
   '982736221843810664156369288039497728']],
 [['660698008644203700473074429819092992',
   '904599195577579897660922571020828672',
   '863371715944324158495051960144625664'],
  ['688710284469165685404738243641999360',
   '869981053223066390571414093008207872',
  

In [19]:
in_json = {
    "in": X_in,
    "out": out
}

In [20]:
with open("maxPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)