In [1]:
from tensorflow.keras.layers import Input, MaxPooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = MaxPooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 2, 2, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.30453079, 0.3455373 , 0.85700244],
         [0.02496087, 0.68109812, 0.95875603],
         [0.54154912, 0.54440417, 0.58525715],
         [0.88786818, 0.35451502, 0.68239083],
         [0.59172416, 0.10230367, 0.86873569]],

        [[0.70574092, 0.81718968, 0.83318974],
         [0.37544715, 0.90991587, 0.18008105],
         [0.63383244, 0.49939633, 0.94083602],
         [0.29234623, 0.41774773, 0.9775676 ],
         [0.30083972, 0.23398012, 0.45529368]],

        [[0.80566034, 0.53924316, 0.29324461],
         [0.31193954, 0.0103429 , 0.85723612],
         [0.34572683, 0.91710721, 0.94363957],
         [0.66609489, 0.36596214, 0.3913392 ],
         [0.18160916, 0.72365282, 0.48540052]],

        [[0.47927146, 0.42374162, 0.59434276],
         [0.26941152, 0.18211572, 0.82634931],
         [0.39593074, 0.33620157, 0.01442567],
         [0.26195157, 0.14637518, 0.20850249],
         [0.12971374, 0.49832269, 0.85234255]],

        [[0.27367145, 0.72452974, 0.26031921],
     

In [5]:
y = model.predict(X)
y

array([[[[0.7057409 , 0.90991586, 0.958756  ],
         [0.88786817, 0.54440415, 0.9775676 ]],

        [[0.8056603 , 0.53924316, 0.85723615],
         [0.6660949 , 0.9171072 , 0.9436396 ]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [7]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [8]:
import json

In [9]:
with open("maxPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [10]:
with open("maxPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [11]:
inputs = Input(shape=(10,10,3))
x = MaxPooling2D(pool_size=2, strides=3)(inputs)
model = Model(inputs, x)

In [12]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 10, 10, 3)]       0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 3, 3, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [13]:
X = np.random.rand(1,10,10,3)
X

array([[[[9.65993586e-01, 2.86740064e-01, 6.46092913e-01],
         [9.79657192e-01, 7.04894608e-02, 2.25727692e-01],
         [1.63480102e-02, 8.59692460e-01, 3.18777287e-01],
         [2.44829188e-01, 6.95082574e-01, 8.42581089e-01],
         [7.22333287e-01, 4.54751914e-01, 6.99985078e-01],
         [5.32035160e-01, 5.32461737e-01, 7.06344205e-01],
         [3.18875650e-01, 9.29949882e-01, 7.13287135e-01],
         [5.88863246e-01, 2.94710274e-01, 5.29519805e-02],
         [6.00602960e-01, 3.08745964e-02, 3.64035518e-01],
         [7.07437015e-01, 8.74881388e-01, 3.50040593e-01]],

        [[7.30319515e-01, 6.34116513e-01, 2.71787245e-01],
         [7.28702418e-01, 3.01280025e-01, 6.12436148e-02],
         [1.61123743e-02, 9.95670084e-02, 4.56461808e-01],
         [8.62142632e-01, 6.53631230e-01, 4.60659447e-01],
         [9.46976954e-01, 7.55910003e-01, 4.18162441e-01],
         [8.97120825e-01, 6.38228256e-01, 9.70948725e-01],
         [6.94496817e-01, 6.75532961e-01, 1.89259554e-

In [14]:
y = model.predict(X)
y

array([[[[0.9796572 , 0.63411653, 0.6460929 ],
         [0.94697696, 0.75591   , 0.8425811 ],
         [0.6944968 , 0.9299499 , 0.9918039 ]],

        [[0.9430022 , 0.77502286, 0.70096034],
         [0.9138255 , 0.71105975, 0.790854  ],
         [0.9475843 , 0.79743564, 0.8429768 ]],

        [[0.6254379 , 0.6840862 , 0.5875524 ],
         [0.9337602 , 0.90715355, 0.9073837 ],
         [0.6475655 , 0.8670486 , 0.8577164 ]]]], dtype=float32)

In [15]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [16]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [17]:
with open("maxPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [18]:
with open("maxPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)