In [1]:
from tensorflow.keras.layers import Input, MaxPooling2D
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = MaxPooling2D(pool_size=2)(inputs)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 5, 5, 3)]         0         
                                                                 
 max_pooling2d (MaxPooling2D  (None, 2, 2, 3)          0         
 )                                                               
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.48850216, 0.09321331, 0.85332612],
         [0.84496756, 0.7795764 , 0.12109799],
         [0.73028024, 0.30310421, 0.51020707],
         [0.96140151, 0.59989949, 0.97756324],
         [0.93625321, 0.34684153, 0.42310131]],

        [[0.27609837, 0.01906993, 0.13781552],
         [0.58882251, 0.20810185, 0.82620907],
         [0.74103594, 0.68708322, 0.65134551],
         [0.31751915, 0.00736138, 0.21706579],
         [0.33679455, 0.47689636, 0.45021002]],

        [[0.09090417, 0.2587238 , 0.41471808],
         [0.43759751, 0.96540039, 0.06554565],
         [0.88061688, 0.97501202, 0.84855213],
         [0.00548949, 0.58019911, 0.6598191 ],
         [0.24852607, 0.54914631, 0.063674  ]],

        [[0.02697956, 0.77545233, 0.8692328 ],
         [0.31050122, 0.11363873, 0.35323089],
         [0.36624655, 0.65015231, 0.68110343],
         [0.84333591, 0.95613639, 0.97572016],
         [0.29138515, 0.84673938, 0.24241197]],

        [[0.55302581, 0.79541176, 0.07496948],
     

In [5]:
y = model.predict(X)
y

1/1 [==============================] - 0s 30ms/step


2023-10-22 19:42:47.267039: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


array([[[[0.84496754, 0.7795764 , 0.85332614],
         [0.9614015 , 0.68708324, 0.97756326]],

        [[0.4375975 , 0.9654004 , 0.8692328 ],
         [0.8806169 , 0.975012  , 0.97572017]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [7]:
import json

In [8]:
with open("maxPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [9]:
inputs = Input(shape=(10,10,3))
x = MaxPooling2D(pool_size=2, strides=3)(inputs)
model = Model(inputs, x)

In [10]:
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 10, 10, 3)]       0         
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 3, 3, 3)          0         
 2D)                                                             
                                                                 
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [11]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.37512817, 0.5641729 , 0.4974857 ],
         [0.41538205, 0.47224858, 0.11706032],
         [0.07640044, 0.34220275, 0.63680247],
         [0.83220726, 0.92702745, 0.5936356 ],
         [0.960865  , 0.65484131, 0.90382201],
         [0.25420919, 0.58229354, 0.51714053],
         [0.28435198, 0.01320203, 0.34704549],
         [0.5366293 , 0.91011852, 0.32633545],
         [0.99100137, 0.2526255 , 0.04232599],
         [0.39196261, 0.90886648, 0.6597151 ]],

        [[0.29830869, 0.51926462, 0.13915042],
         [0.4889853 , 0.51424009, 0.75465903],
         [0.93713835, 0.397958  , 0.20989932],
         [0.32209555, 0.52508299, 0.63443281],
         [0.14408686, 0.66008294, 0.13806776],
         [0.62699816, 0.90600042, 0.56895258],
         [0.58121376, 0.80103256, 0.44657054],
         [0.59427662, 0.75233325, 0.57963649],
         [0.71953207, 0.81024282, 0.21128334],
         [0.73682019, 0.32007903, 0.67071529]],

        [[0.80006018, 0.11776644, 0.35329049],
         

In [12]:
y = model.predict(X)
y

1/1 [==============================] - 0s 27ms/step


array([[[[0.4889853 , 0.5641729 , 0.75465906],
         [0.960865  , 0.92702746, 0.903822  ],
         [0.5942766 , 0.9101185 , 0.5796365 ]],

        [[0.5655196 , 0.80397266, 0.87354416],
         [0.73181504, 0.89869106, 0.92891836],
         [0.63684857, 0.9362948 , 0.95604604]],

        [[0.89681286, 0.9395762 , 0.7481612 ],
         [0.89400744, 0.92957413, 0.76228076],
         [0.9028809 , 0.89010954, 0.87178284]]]], dtype=float32)

In [13]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [14]:
with open("maxPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)