In [1]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(3,))
x = Dense(2, activation='relu')(inputs)
outputs = Dense(1)(x)
model = Model(inputs, outputs)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 3)]               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 8         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 11
Trainable params: 11
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(3, 2) dtype=float32, numpy=
 array([[ 0.6173352 , -0.80709445],
        [-0.53739315, -0.64572155],
        [ 1.057004  , -0.6135417 ]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.45618665],
        [0.5399432 ]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [5]:
X = np.random.rand(1,3)
X

array([[0.39493793, 0.16756107, 0.28846495]])

In [6]:
y = model.predict(X)
y

array([[0.20923984]], dtype=float32)

In [7]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist(),
    "Dense32weights": (model.weights[0].numpy()*1000).round().astype(int).flatten().tolist(),
    "Dense21weights": (model.weights[2].numpy()*1000).round().astype(int).flatten().tolist()
}

In [8]:
out_json = {
    "out": (y*(1000**3)).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [10]:
with open("model1_input.json", "w") as f:
    json.dump(in_json, f)

In [11]:
with open("model1_output.json", "w") as f:
    json.dump(out_json, f)