In [1]:
from tensorflow.keras.layers import Input, AveragePooling2D, Lambda
from tensorflow.keras import Model
import numpy as np

In [2]:
inputs = Input(shape=(5,5,3))
x = AveragePooling2D(pool_size=2)(inputs)
x = Lambda(lambda x: x*4)(x)
model = Model(inputs, x)

In [3]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 5, 5, 3)]         0         
_________________________________________________________________
average_pooling2d (AveragePo (None, 2, 2, 3)           0         
_________________________________________________________________
lambda (Lambda)              (None, 2, 2, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [4]:
X = np.random.rand(1,5,5,3)
X

array([[[[0.83128186, 0.15650764, 0.23798145],
         [0.00277366, 0.8374127 , 0.95278315],
         [0.3074389 , 0.21931738, 0.14886067],
         [0.13590018, 0.98728255, 0.12085182],
         [0.47212572, 0.51380922, 0.74891219]],

        [[0.74680338, 0.2533205 , 0.5039968 ],
         [0.14475403, 0.00791911, 0.4361197 ],
         [0.69925568, 0.77507624, 0.40388991],
         [0.29508251, 0.99375606, 0.84959701],
         [0.88844918, 0.33910189, 0.9617212 ]],

        [[0.76480625, 0.591287  , 0.0714191 ],
         [0.94371681, 0.1695303 , 0.4476252 ],
         [0.54372616, 0.83818804, 0.95211573],
         [0.30485104, 0.15165265, 0.94709317],
         [0.90827137, 0.58854675, 0.01857002]],

        [[0.70123418, 0.43090173, 0.7096038 ],
         [0.20637783, 0.20096581, 0.22956612],
         [0.81978383, 0.16775403, 0.67412096],
         [0.1011535 , 0.35596916, 0.36702071],
         [0.5874605 , 0.79341372, 0.93292159]],

        [[0.77997124, 0.46311399, 0.5465576 ],
     

In [12]:
y = model.predict(X)
y

array([[[[1.7256129, 1.2551599, 2.1308813],
         [1.4376774, 2.9754324, 1.5231993]],

        [[2.6161351, 1.3926848, 1.4582142],
         [1.7695144, 1.5135639, 2.9403505]]]], dtype=float32)

In [6]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [7]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [9]:
import json

In [9]:
with open("sumPooling2D_input.json", "w") as f:
    json.dump(in_json, f)

In [10]:
with open("sumPooling2D_output.json", "w") as f:
    json.dump(out_json, f)

In [20]:
inputs = Input(shape=(10,10,3))
x = AveragePooling2D(pool_size=2, strides=3)(inputs)
x = Lambda(lambda x: x*4)(x)
model = Model(inputs, x)

In [21]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 10, 10, 3)]       0         
_________________________________________________________________
average_pooling2d_2 (Average (None, 3, 3, 3)           0         
_________________________________________________________________
lambda_2 (Lambda)            (None, 3, 3, 3)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [22]:
X = np.random.rand(1,10,10,3)
X

array([[[[0.31514958, 0.03200121, 0.29129004],
         [0.35725668, 0.87252739, 0.77162311],
         [0.61707883, 0.7945887 , 0.48907944],
         [0.98197306, 0.88814753, 0.69652672],
         [0.2518265 , 0.82753267, 0.57464263],
         [0.62115028, 0.76805041, 0.65967975],
         [0.32491691, 0.93353364, 0.74831234],
         [0.45570461, 0.96830864, 0.8476189 ],
         [0.02149766, 0.27808247, 0.18207897],
         [0.15949257, 0.69372265, 0.43455872]],

        [[0.70915807, 0.60410698, 0.94721792],
         [0.5621233 , 0.65546021, 0.27357865],
         [0.00414209, 0.08635782, 0.30528659],
         [0.11492599, 0.15002234, 0.58496289],
         [0.72848003, 0.55169839, 0.91708802],
         [0.43479205, 0.08069621, 0.68404234],
         [0.3946513 , 0.20447291, 0.10467492],
         [0.78817621, 0.63518792, 0.00827133],
         [0.0853401 , 0.75656605, 0.95034115],
         [0.92239164, 0.06871402, 0.37783711]],

        [[0.36000095, 0.35659628, 0.6507159 ],
         

In [23]:
y = model.predict(X)
y

array([[[[1.9436876 , 2.1640959 , 2.2837098 ],
         [2.0772057 , 2.4174008 , 2.7732203 ],
         [1.963449  , 2.741503  , 1.7088774 ]],

        [[1.6524236 , 3.0454814 , 1.8892637 ],
         [2.4567943 , 2.5845926 , 2.3090153 ],
         [1.6444083 , 1.7326821 , 1.7165766 ]],

        [[2.6089072 , 3.043223  , 1.8332952 ],
         [1.7920854 , 2.1280923 , 1.2828767 ],
         [0.72196686, 2.1598206 , 1.3420006 ]]]], dtype=float32)

In [24]:
in_json = {
    "in": (X*1000).round().astype(int).flatten().tolist()
}

In [25]:
out_json = {
    "out": (y*1000).round().astype(int).flatten().tolist()
}

In [26]:
with open("sumPooling2D_stride_input.json", "w") as f:
    json.dump(in_json, f)

In [27]:
with open("sumPooling2D_stride_output.json", "w") as f:
    json.dump(out_json, f)